// GENERATED by scripts/google-fonts.ts — do not edit by hand.
//
// Google Fonts as of 2026-09-21: 1818 families with a latin cut, each with the
// licence it is published under, who drew it, and the weights it can be asked for. One family
// per line, `family|category|licence|by|weights` (see `font-catalog.ts`).
//
// Loaded only by the dynamic import in `FontCatalog.tsx`, so none of this weight is on the
// editor's first paint and none of it is fetched from Google (#329, L27, DRIFT §12).
export const GOOGLE_FONTS = `ABeeZee|sans|OFL 1.1|Anja Meiners|400
Abel|sans|OFL 1.1|MADType|400
Abhaya Libre|serif|OFL 1.1|Mooniak|400;500;600;700;800
Aboreto|display|OFL 1.1|Dominik Jáger|400
Abril Fatface|display|OFL 1.1|TypeTogether|400
Abyssinica SIL|serif|OFL 1.1|SIL International|400
Aclonica|sans|Apache 2.0|Astigmatic|400
Acme|sans|OFL 1.1|Juan Pablo del Peral, HT Fonts|400
Actor|sans|OFL 1.1|Thomas Junold|400
Adamina|serif|OFL 1.1|Cyreal|400
ADLaM Display|display|OFL 1.1|Mark Jamra, Neil Patel, Andrew Footit|400
Advent Pro|sans|OFL 1.1|VivaRado|100..900
Afacad|sans|OFL 1.1|Kristian Möller, Dicotype|400..700
Afacad Flux|sans|OFL 1.1|Kristian Möller, Dicotype|100..1000
Agbalumo|display|OFL 1.1|Raphael Alẹ́gbẹ́lẹ́yẹ̀, Sorkin Type, Eben Sorkin|400
Agdasima|sans|OFL 1.1|The DocRepair Project, Patric King|400;700
Agu Display|display|OFL 1.1|Seun Badejo|400
Aguafina Script|handskrift|OFL 1.1|Sudtipos|400
Akatab|sans|OFL 1.1|SIL International|400;500;600;700;800;900
Akaya Kanadaka|display|OFL 1.1|Vaishnavi Murthy, Juan Luis Blanco|400
Akaya Telivigala|display|OFL 1.1|Vaishnavi Murthy, Juan Luis Blanco|400
Akronim|display|OFL 1.1|Grzegorz Klimczewski|400
Akshar|sans|OFL 1.1|Tall Chai|300..700
Akt|sans|OFL 1.1|Dmitry Grenev|100..900
Aladin|display|OFL 1.1|Sudtipos|400
Alan Sans|sans|OFL 1.1|Raphaël Ronot, Samar Zureik|300..900
Alata|sans|OFL 1.1|Spyros Zevelakis, Eben Sorkin|400
Alatsi|sans|OFL 1.1|Spyros Zevelakis, Eben Sorkin|400
Albert Sans|sans|OFL 1.1|Andreas Rasmussen|100..900
Aldrich|sans|OFL 1.1|MADType|400
Alef|sans|OFL 1.1|Hagilda, Mushon Zer-Aviv|400;700
Alegreya|serif|OFL 1.1|Juan Pablo del Peral, HT Fonts|400..900
Alegreya Sans|sans|OFL 1.1|Juan Pablo del Peral, HT Fonts|100;300;400;500;700;800;900
Alegreya Sans SC|sans|OFL 1.1|Juan Pablo del Peral, HT Fonts|100;300;400;500;700;800;900
Alegreya SC|serif|OFL 1.1|Juan Pablo del Peral, HT Fonts|400;500;700;800;900
Aleo|serif|OFL 1.1|Alessio Laiso|100..900
Alex Brush|handskrift|OFL 1.1|Robert Leuschke|400
Alexandria|sans|OFL 1.1|Mohamed Gaber, Julieta Ulanovsky|100..900
Alfa Slab One|display|OFL 1.1|JM Solé|400
Alice|serif|OFL 1.1|Ksenya Erulevich, Cyreal|400
Alien Block|display|OFL 1.1|Kensuke Uchida|400
Alike|serif|OFL 1.1|Sveta Sebyakina, Cyreal|400
Alike Angular|serif|OFL 1.1|Sveta Sebyakina, Cyreal|400
Alkalami|serif|OFL 1.1|SIL International|400
Alkatra|display|OFL 1.1|Suman Bhandary|400..700
Allan|display|OFL 1.1|Anton Koovit|400;700
Allerta|sans|OFL 1.1|Matt McInerney|400
Allerta Stencil|sans|OFL 1.1|Matt McInerney|400
Allison|handskrift|OFL 1.1|Robert Leuschke|400
Allura|handskrift|OFL 1.1|Robert Leuschke|400
Almarai|sans|OFL 1.1|Boutros Fonts, Mourad Boutros|300;400;700;800
Almendra|serif|OFL 1.1|Ana Sanfelippo|400;700
Almendra Display|display|OFL 1.1|Ana Sanfelippo|400
Almendra SC|serif|OFL 1.1|Ana Sanfelippo|400
Alumni Sans|sans|OFL 1.1|Robert Leuschke|100..900
Alumni Sans Collegiate One|sans|OFL 1.1|Robert Leuschke|400
Alumni Sans Inline One|display|OFL 1.1|Robert Leuschke|400
Alumni Sans Pinstripe|sans|OFL 1.1|Robert Leuschke|400
Alumni Sans SC|sans|OFL 1.1|Robert Leuschke|100..900
Alyamama|serif|OFL 1.1|Yazeed Omar|300..900
Amarante|display|OFL 1.1|Karolina Lach|400
Amaranth|sans|OFL 1.1|Gesine Todt|400;700
Amarna|sans|OFL 1.1|Ishtār van Looy|100..700
Amatic SC|handskrift|OFL 1.1|Vernon Adams, Ben Nathan, Thomas Jockin|400;700
Amethysta|serif|OFL 1.1|Cyreal|400
Amiko|sans|OFL 1.1|Impallari Type|400;600;700
Amiri|serif|OFL 1.1|Khaled Hosny, Sebastian Kosch|400;700
Amiri Quran|serif|OFL 1.1|Khaled Hosny, Sebastian Kosch|400
Amita|handskrift|OFL 1.1|Eduardo Tunni, Brian Bonislawsky|400;700
Anaheim|sans|OFL 1.1|Vernon Adams|400..800
Ancizar Sans|sans|OFL 1.1|Universidad Nacional de Colombia (UNAL), César Puertas, Viviana Monsalve, Julián Moncada|100..1000
Ancizar Serif|serif|OFL 1.1|Universidad Nacional de Colombia (UNAL), César Puertas, Viviana Monsalve, Julián Moncada|300..900
Andada Pro|serif|OFL 1.1|HT Fonts, Carolina Giovagnoli|400..840
Andika|sans|OFL 1.1|SIL International|400;700
Anek Bangla|sans|OFL 1.1|Ek Type|100..800
Anek Devanagari|sans|OFL 1.1|Ek Type|100..800
Anek Gujarati|sans|OFL 1.1|Ek Type|100..800
Anek Gurmukhi|sans|OFL 1.1|Ek Type|100..800
Anek Kannada|sans|OFL 1.1|Ek Type|100..800
Anek Latin|sans|OFL 1.1|Ek Type|100..800
Anek Malayalam|sans|OFL 1.1|Ek Type|100..800
Anek Odia|sans|OFL 1.1|Ek Type|100..800
Anek Tamil|sans|OFL 1.1|Ek Type|100..800
Anek Telugu|sans|OFL 1.1|Ek Type|100..800
Angkor|display|OFL 1.1|Danh Hong|400
Annapurna SIL|serif|OFL 1.1|SIL International|400;700
Annie Use Your Telescope|handskrift|OFL 1.1|Kimberly Geswein|400
Anonymous Pro|mono|OFL 1.1|Mark Simonson|400;700
Anta|sans|OFL 1.1|Sergej Lebedev|400
Antic|sans|OFL 1.1|Santiago Orozco|400
Antic Didone|serif|OFL 1.1|Santiago Orozco|400
Antic Slab|serif|OFL 1.1|Santiago Orozco|400
Anton|sans|OFL 1.1|Vernon Adams|400
Anton SC|sans|OFL 1.1|Vernon Adams|400
Antonio|sans|OFL 1.1|Vernon Adams|100..700
Anuphan|sans|OFL 1.1|Cadson Demak|100..700
Anybody|display|OFL 1.1|Tyler Finck|100..900
Aoboshi One|serif|OFL 1.1|Natsumi Matsuba|400
AR One Sans|sans|OFL 1.1|Niteesh Yadav|400..700
Arapey|serif|OFL 1.1|Eduardo Tunni|400
Arbutus|serif|OFL 1.1|Karolina Lach|400
Arbutus Slab|serif|OFL 1.1|Karolina Lach|400
Architects Daughter|handskrift|OFL 1.1|Kimberly Geswein|400
Archivo|sans|OFL 1.1|Omnibus-Type|100..900
Archivo Black|sans|OFL 1.1|Omnibus-Type|400
Archivo Narrow|sans|OFL 1.1|Omnibus-Type|400..700
Are You Serious|handskrift|OFL 1.1|Robert Leuschke|400
Aref Ruqaa|serif|OFL 1.1|Abdullah Aref, Khaled Hosny, Hermann Zapf|400;700
Aref Ruqaa Ink|serif|OFL 1.1|Abdullah Aref, Khaled Hosny, Hermann Zapf|400;700
Arima|display|OFL 1.1|Natanael Gama, Joana Correia, Rosalie Wagner|100..700
Arimo|sans|OFL 1.1|Steve Matteson|400..700
Arizonia|handskrift|OFL 1.1|Robert Leuschke|400
Armata|sans|OFL 1.1|Viktoriya Grabowska|400
Arsenal|sans|OFL 1.1|Andrij Shevchenko|400;700
Arsenal SC|sans|OFL 1.1|Andrij Shevchenko|400;700
Artifika|serif|OFL 1.1|Cyreal|400
Arvo|serif|OFL 1.1|Anton Koovit|400;700
Arya|sans|OFL 1.1|Eduardo Tunni|400;700
Asap|sans|OFL 1.1|Omnibus-Type|100..900
Asap Condensed|sans|OFL 1.1|Omnibus-Type|200;300;400;500;600;700;800;900
Asap Sharp|sans|OFL 1.1|Omnibus-Type|100..900
Asar|serif|OFL 1.1|Sorkin Type|400
Asimovian|sans|OFL 1.1|Carolina Short|400
Asset|display|OFL 1.1|Riccardo De Franceschi, Eben Sorkin|400
Assistant|sans|OFL 1.1|Adobe Systems Inc., Ben Nathan|200..800
Asta Sans|sans|OFL 1.1|42dot|300..800
Astloch|display|OFL 1.1|Dan Rhatigan|400;700
Asul|serif|OFL 1.1|Mariela Monsalve|400;700
Athiti|sans|OFL 1.1|Cadson Demak|200;300;400;500;600;700
Atkinson Hyperlegible|sans|OFL 1.1|Braille Institute, Applied Design Works, Elliott Scott, Megan Eiswerth, Linus Boman, Theodore Petrosky|400;700
Atkinson Hyperlegible Mono|sans|OFL 1.1|Braille Institute, Applied Design Works, Elliott Scott, Megan Eiswerth, Letters From Sweden|200..800
Atkinson Hyperlegible Next|sans|OFL 1.1|Braille Institute, Applied Design Works, Elliott Scott, Megan Eiswerth, Letters From Sweden|200..800
Atma|display|OFL 1.1|Black Foundry|300;400;500;600;700
Atomic Age|display|OFL 1.1|James Grieshaber|400
Aubrey|display|OFL 1.1|Cyreal|400
Audiowide|display|OFL 1.1|Astigmatic|400
Autour One|display|OFL 1.1|Sorkin Type|400
Average|serif|OFL 1.1|Eduardo Tunni|400
Average Sans|sans|OFL 1.1|Eduardo Tunni|400
Averia Gruesa Libre|display|OFL 1.1|Dan Sayers|400
Averia Libre|display|OFL 1.1|Dan Sayers|300;400;700
Averia Sans Libre|display|OFL 1.1|Dan Sayers|300;400;700
Averia Serif Libre|display|OFL 1.1|Dan Sayers|300;400;700
Azeret Mono|mono|OFL 1.1|Displaay, Martin Vácha|100..900
B612|sans|OFL 1.1|PolarSys, Nicolas Chauveau, Thomas Paillot, Jonathan Favre-Lamarine, Jean-Luc Vinot|400;700
B612 Mono|mono|OFL 1.1|Nicolas Chauveau, Thomas Paillot, Jonathan Favre-Lamarine, Jean-Luc Vinot|400;700
Babylonica|handskrift|OFL 1.1|Robert Leuschke|400
Bacasime Antique|serif|OFL 1.1|The DocRepair Project, Claus Eggers Sørensen|400
Bad Script|handskrift|OFL 1.1|Gaslight|400
Badeen Display|display|OFL 1.1|Hani Alasadi|400
Bagel Fat One|display|OFL 1.1|Kyungwon Kim, JAMO|400
Bahiana|display|OFL 1.1|Omnibus-Type|400
Bahianita|display|OFL 1.1|Omnibus-Type|400
Bai Jamjuree|sans|OFL 1.1|Cadson Demak|200;300;400;500;600;700
Bakbak One|display|OFL 1.1|Saumya Kishore, Sanchit Sawaria|400
Ballet|handskrift|OFL 1.1|Omnibus-Type, Maximiliano Sproviero|400
Baloo 2|display|OFL 1.1|Ek Type|400..800
Baloo Bhai 2|display|OFL 1.1|Ek Type|400..800
Baloo Bhaijaan 2|display|OFL 1.1|Ek Type|400..800
Baloo Bhaina 2|display|OFL 1.1|Ek Type|400..800
Baloo Chettan 2|display|OFL 1.1|Ek Type|400..800
Baloo Da 2|display|OFL 1.1|Ek Type|400..800
Baloo Paaji 2|display|OFL 1.1|Ek Type|400..800
Baloo Tamma 2|display|OFL 1.1|Ek Type|400..800
Baloo Tammudu 2|display|OFL 1.1|Ek Type|400..800
Baloo Thambi 2|display|OFL 1.1|Ek Type|400..800
Balsamiq Sans|display|OFL 1.1|Michael Angeles|400;700
Balthazar|serif|OFL 1.1|Dario Manuel Muhafara|400
Bangers|display|OFL 1.1|Vernon Adams|400
Barlow|sans|OFL 1.1|Jeremy Tribby|100;200;300;400;500;600;700;800;900
Barlow Condensed|sans|OFL 1.1|Jeremy Tribby|100;200;300;400;500;600;700;800;900
Barlow Semi Condensed|sans|OFL 1.1|Jeremy Tribby|100;200;300;400;500;600;700;800;900
Barriecito|display|OFL 1.1|Omnibus-Type|400
Barrio|display|OFL 1.1|Omnibus-Type|400
Basic|sans|OFL 1.1|Magnus Gaarde|400
Baskervville|serif|OFL 1.1|ANRT|400..700
Baskervville SC|serif|OFL 1.1|ANRT|400..700
Battambang|display|OFL 1.1|Danh Hong|100;300;400;700;900
Baumans|display|OFL 1.1|Cyreal|400
Bayon|sans|OFL 1.1|Danh Hong|400
BBH Bartle|sans|OFL 1.1|Studio DRAMA|400
BBH Bogle|sans|OFL 1.1|Studio DRAMA|400
BBH Hegarty|sans|OFL 1.1|Studio DRAMA|400
Be Vietnam Pro|sans|OFL 1.1|Lâm Bảo, Tony Le, ViệtAnh Nguyễn|100;200;300;400;500;600;700;800;900
Beau Rivage|handskrift|OFL 1.1|Robert Leuschke|400
Bebas Neue|sans|OFL 1.1|Ryoichi Tsunekawa|400
Beiruti|sans|OFL 1.1|Boutros Fonts, Arlette Boutros, Volker Schnebel|200..900
Belanosima|sans|OFL 1.1|The DocRepair Project, Santiago Orozco|400;600;700
Belgrano|serif|OFL 1.1|LatinoType|400
Bellefair|serif|OFL 1.1|Nick Shinn, Liron Lavi Turkenic|400
Belleza|sans|OFL 1.1|Eduardo Tunni|400
Bellota|display|OFL 1.1|Kemie Guaida|300;400;700
Bellota Text|display|OFL 1.1|Kemie Guaida|300;400;700
BenchNine|sans|OFL 1.1|Vernon Adams|300;400;700
Benne|serif|OFL 1.1|John Harrington|400
Bentham|serif|OFL 1.1|Ben Weiner|400
Berkshire Swash|handskrift|OFL 1.1|Astigmatic|400
Besley|serif|OFL 1.1|Owen Earl|400..900
Betania Patmos|handskrift|OFL 1.1|Carolina Giovagnoli|400
Betania Patmos GDL|handskrift|OFL 1.1|Carolina Giovagnoli|400
Betania Patmos In|handskrift|OFL 1.1|Carolina Giovagnoli|400
Betania Patmos In GDL|handskrift|OFL 1.1|Carolina Giovagnoli|400
Beth Ellen|handskrift|OFL 1.1|Rob Jelinski, Alyson Fraser Diaz|400
Bevan|serif|OFL 1.1|Vernon Adams|400
BhuTuka Expanded One|serif|OFL 1.1|Erin McLaughlin|400
Big Shoulders|display|OFL 1.1|Patric King|100..900
Big Shoulders Inline|display|OFL 1.1|Patric King|100..900
Big Shoulders Stencil|display|OFL 1.1|Patric King|100..900
Bigelow Rules|display|OFL 1.1|Astigmatic|400
Bigshot One|display|OFL 1.1|Gesine Todt|400
Bilbo|handskrift|OFL 1.1|Robert Leuschke|400
Bilbo Swash Caps|handskrift|OFL 1.1|TypeSETit|400
BioRhyme|serif|OFL 1.1|Aoife Mooney|200..800
BioRhyme Expanded|serif|OFL 1.1|Aoife Mooney|200;300;400;700;800
Birthstone|handskrift|OFL 1.1|Robert Leuschke|400
Birthstone Bounce|handskrift|OFL 1.1|Robert Leuschke|400;500
Biryani|sans|OFL 1.1|Dan Reynolds, Mathieu Réguer|200;300;400;600;700;800;900
Bitcount|display|OFL 1.1|Petr van Blokland|100..900
Bitcount Grid Double|display|OFL 1.1|Petr van Blokland|100..900
Bitcount Grid Double Ink|display|OFL 1.1|Petr van Blokland|100..900
Bitcount Grid Single|display|OFL 1.1|Petr van Blokland|100..900
Bitcount Grid Single Ink|display|OFL 1.1|Petr van Blokland|100..900
Bitcount Ink|display|OFL 1.1|Petr van Blokland|100..900
Bitcount Prop Double|display|OFL 1.1|Petr van Blokland|100..900
Bitcount Prop Double Ink|display|OFL 1.1|Petr van Blokland|100..900
Bitcount Prop Single|display|OFL 1.1|Petr van Blokland|100..900
Bitcount Prop Single Ink|display|OFL 1.1|Petr van Blokland|100..900
Bitcount Single|display|OFL 1.1|Petr van Blokland|100..900
Bitcount Single Ink|display|OFL 1.1|Petr van Blokland|100..900
Bitter|serif|OFL 1.1|Sol Matas|100..900
BIZ UDGothic|sans|OFL 1.1|Type Bank Co., Morisawa Inc.|400;700
BIZ UDMincho|serif|OFL 1.1|Type Bank Co., Morisawa Inc.|400;700
BIZ UDPGothic|sans|OFL 1.1|Type Bank Co., Morisawa Inc.|400;700
BIZ UDPMincho|serif|OFL 1.1|Type Bank Co., Morisawa Inc.|400;700
BJCree|serif|OFL 1.1|SIL International|400;500;600;700
Black And White Picture|display|OFL 1.1|AsiaSoft Inc.|400
Black Han Sans|sans|OFL 1.1|Zess Type|400
Black Ops One|display|OFL 1.1|James Grieshaber, Eben Sorkin|400
Blaka|display|OFL 1.1|Mohamed Gaber|400
Blaka Hollow|display|OFL 1.1|Mohamed Gaber|400
Blaka Ink|display|OFL 1.1|Mohamed Gaber|400
Blinker|sans|OFL 1.1|Juergen Huber|100;200;300;400;600;700;800;900
Bodoni Moda|serif|OFL 1.1|Owen Earl|400..900
Bodoni Moda SC|serif|OFL 1.1|Owen Earl|400..900
Bokor|display|OFL 1.1|Danh Hong|400
Boldonse|display|OFL 1.1|Universitype|400
Bona Nova|serif|OFL 1.1|Capitalics, Mateusz Machalski, Andrzej Heidrich|400;700
Bona Nova SC|serif|OFL 1.1|Capitalics, Mateusz Machalski, Andrzej Heidrich|400;700
Bonbon|handskrift|OFL 1.1|Cyreal|400
Bonheur Royale|handskrift|OFL 1.1|Robert Leuschke|400
Boogaloo|display|OFL 1.1|John Vargas Beltrán|400
Borel|handskrift|OFL 1.1|Rosalie Wagner|400
Bowlby One|display|OFL 1.1|Vernon Adams|400
Bowlby One SC|display|OFL 1.1|Vernon Adams|400
Bpmf Huninn|sans|OFL 1.1|But Ko, justfont|400
Bpmf Iansui|handskrift|OFL 1.1|But Ko|400
Bpmf Zihi Kai Std|sans|OFL 1.1|But Ko|400
Braah One|sans|OFL 1.1|Ashish Kumar|400
Brawler|serif|OFL 1.1|Cyreal|400;700
Bree Serif|serif|OFL 1.1|TypeTogether|400
Bricolage Grotesque|sans|OFL 1.1|Mathieu Triay|200..800
Bruno Ace|display|OFL 1.1|Astigmatic|400
Bruno Ace SC|display|OFL 1.1|Astigmatic|400
Brygada 1918|serif|OFL 1.1|Capitalics, Mateusz Machalski, Borys Kosmynka, Ania Wieluńska, Przemysław Hoffer|400..700
Bubblegum Sans|display|OFL 1.1|Sudtipos|400
Bubbler One|sans|OFL 1.1|Brenda Gallo|400
Buda|display|OFL 1.1|Adèle Antignac|300
Buenard|serif|OFL 1.1|Gustavo Ibarra|400..700
Bungee|display|OFL 1.1|David Jonathan Ross|400
Bungee Hairline|display|OFL 1.1|David Jonathan Ross|400
Bungee Inline|display|OFL 1.1|David Jonathan Ross|400
Bungee Outline|display|OFL 1.1|David Jonathan Ross|400
Bungee Shade|display|OFL 1.1|David Jonathan Ross|400
Bungee Spice|display|OFL 1.1|David Jonathan Ross|400
Bungee Tint|display|OFL 1.1|David Jonathan Ross|400
Butcherman|display|OFL 1.1|Typomondo|400
Butterfly Kids|handskrift|OFL 1.1|Tart Workshop|400
Bytesized|sans|OFL 1.1|Baltdev|400
Caacupe One|display|OFL 1.1|Magdalena Alonso Rebollo|400
Cabin|sans|OFL 1.1|Impallari Type, Rodrigo Fuenzalida|400..700
Cabin Condensed|sans|OFL 1.1|Impallari Type|400;500;600;700
Cabin Sketch|display|OFL 1.1|Impallari Type|400;700
Cactus Classical Serif|serif|OFL 1.1|Henry Chan, Tian Haidong, Moonlit Owen|400
Caesar Dressing|display|OFL 1.1|Open Window|400
Cagliostro|sans|OFL 1.1|MADType|400
Cairo|sans|OFL 1.1|Mohamed Gaber, Accademia di Belle Arti di Urbino|200..1000
Cairo Play|sans|OFL 1.1|Mohamed Gaber, Accademia di Belle Arti di Urbino|200..1000
Cal Sans|sans|OFL 1.1|Mark Davis, Cal.com Inc.|400
Caladea|serif|OFL 1.1|HT Fonts, Carolina Giovagnoli, Andrés Torresi|400;700
Calistoga|display|OFL 1.1|Yvonne Schüttler, Sorkin Type, Eben Sorkin|400
Calligraffitti|handskrift|Apache 2.0|Open Window|400
Cambay|sans|OFL 1.1|Pooja Saxena|400;700
Cambo|serif|OFL 1.1|HT Fonts, Carolina Giovagnoli, Andres Torresi|400
Candal|sans|OFL 1.1|Vernon Adams|400
Cantarell|sans|OFL 1.1|Dave Crossland|400;700
Cantata One|serif|OFL 1.1|Joana Correia|400
Cantora One|sans|OFL 1.1|Impallari Type|400
Caprasimo|display|OFL 1.1|The DocRepair Project, Phaedra Charles, Flavia Zimbardi|400
Capriola|sans|OFL 1.1|Viktoriya Grabowska|400
Caramel|handskrift|OFL 1.1|Robert Leuschke|400
Carattere|handskrift|OFL 1.1|Robert Leuschke|400
Cardo|serif|OFL 1.1|David Perry|400;700
Carlito|sans|OFL 1.1|Łukasz Dziedzic|400;700
Carme|sans|OFL 1.1|Rubén Prol|400
Carrois Gothic|sans|OFL 1.1|Carrois Apostrophe|400
Carrois Gothic SC|sans|OFL 1.1|Carrois Apostrophe|400
Carter One|display|OFL 1.1|Vernon Adams|400
Cascadia Code|sans|OFL 1.1|Aaron Bell, Mohamad Dakak, Viktoriya Grabowska, Liron Lavi Turkenich|200..700
Cascadia Mono|sans|OFL 1.1|Aaron Bell, Mohamad Dakak, Viktoriya Grabowska, Liron Lavi Turkenich|200..700
Castoro|serif|OFL 1.1|Tiro Typeworks, John Hudson, Paul Hanslow, Kaja Słojewska|400
Castoro Titling|display|OFL 1.1|Tiro Typeworks, John Hudson|400
Catamaran|sans|OFL 1.1|Pria Ravichandran|100..900
Caudex|serif|OFL 1.1|Nidud|400;700
Cause|handskrift|OFL 1.1|Saurabh Sharma|100..900
Caveat|handskrift|OFL 1.1|Impallari Type|400..700
Caveat Brush|handskrift|OFL 1.1|Impallari Type|400
Cedarville Cursive|handskrift|OFL 1.1|Kimberly Geswein|400
Ceviche One|display|OFL 1.1|Miguel Hernandez|400
Chakra Petch|sans|OFL 1.1|Cadson Demak|300;400;500;600;700
Changa|sans|OFL 1.1|Eduardo Tunni|200..800
Changa One|display|OFL 1.1|Eduardo Tunni|400
Chango|display|OFL 1.1|Fontstage|400
Charis SIL|serif|OFL 1.1|SIL International|400;700
Charm|handskrift|OFL 1.1|Cadson Demak|400;700
Charmonman|handskrift|OFL 1.1|Cadson Demak|400;700
Chathura|sans|OFL 1.1|Appaji Ambarisha Darbha|100;300;400;700;800
Chau Philomene One|sans|OFL 1.1|Vicente Lamónaca|400
Chela One|display|OFL 1.1|Miguel Hernandez|400
Chelsea Market|display|OFL 1.1|Tart Workshop|400
Cherish|handskrift|OFL 1.1|Robert Leuschke|400
Cherry Bomb One|display|OFL 1.1|Satsuyako|400
Cherry Cream Soda|display|Apache 2.0|Font Diner|400
Cherry Swash|display|OFL 1.1|Nataliya Kasatkina|400;700
Chewy|display|Apache 2.0|Sideshow|400
Chicle|display|OFL 1.1|Sudtipos|400
Chilanka|handskrift|OFL 1.1|SMC, Santhosh Thottingal|400
Chiron GoRound TC|sans|OFL 1.1|Tamcy|200..900
Chiron Hei HK|sans|OFL 1.1|Tamcy|200..900
Chiron Sung HK|serif|OFL 1.1|Tamcy|200..900
Chivo|sans|OFL 1.1|Omnibus-Type|100..900
Chivo Mono|mono|OFL 1.1|Omnibus-Type|100..900
Chocolate Classical Sans|sans|OFL 1.1|Moonlit Owen|400
Chokokutai|display|OFL 1.1|Font Zone 108|400
Chonburi|display|OFL 1.1|Cadson Demak|400
Cinzel|serif|OFL 1.1|Natanael Gama|400..900
Cinzel Decorative|display|OFL 1.1|Natanael Gama|400;700;900
Clicker Script|handskrift|OFL 1.1|Astigmatic|400
Climate Crisis|display|OFL 1.1|Daniel Coull, Eino Korkala|400
Coda|display|OFL 1.1|Vernon Adams|400;800
Codystar|display|OFL 1.1|Neapolitan|300;400
Coiny|display|OFL 1.1|Marcelo Magalhães|400
Combo|display|OFL 1.1|Eduardo Tunni|400
Comfortaa|display|OFL 1.1|Johan Aakerlund|300..700
Comforter|handskrift|OFL 1.1|Robert Leuschke|400
Comforter Brush|handskrift|OFL 1.1|Robert Leuschke|400
Comic Neue|handskrift|OFL 1.1|Craig Rozynski, Hrant Papazian|300;400;700
Comic Relief|display|OFL 1.1|Jeff Davis|400;700
Coming Soon|handskrift|Apache 2.0|Open Window|400
Comme|sans|OFL 1.1|Vernon Adams|100..900
Commissioner|sans|OFL 1.1|Kostas Bartsokas|100..900
Concert One|display|OFL 1.1|Johan Kallas, Mihkel Virkus|400
Condiment|handskrift|OFL 1.1|Sudtipos|400
Contrail One|display|OFL 1.1|Riccardo De Franceschi|400
Convergence|sans|OFL 1.1|Nicolás Silva, John Vargas Beltrán|400
Cookie|handskrift|OFL 1.1|Ania Kruk|400
Copse|serif|OFL 1.1|Dan Rhatigan|400
Coral Pixels|display|OFL 1.1|Tanukizamurai|400
Corben|display|OFL 1.1|Vernon Adams|400;700
Corinthia|handskrift|OFL 1.1|Robert Leuschke|400;700
Cormorant|serif|OFL 1.1|Christian Thalmann|300..700
Cormorant Garamond|serif|OFL 1.1|Christian Thalmann|300..700
Cormorant Infant|serif|OFL 1.1|Christian Thalmann|300..700
Cormorant SC|serif|OFL 1.1|Christian Thalmann|300;400;500;600;700
Cormorant Unicase|serif|OFL 1.1|Christian Thalmann|300;400;500;600;700
Cormorant Upright|serif|OFL 1.1|Christian Thalmann|300;400;500;600;700
Cossette Texte|sans|OFL 1.1|Cossette|400;700
Cossette Titre|sans|OFL 1.1|Cossette|400;700
Courgette|handskrift|OFL 1.1|Karolina Lach|400
Courier Prime|mono|OFL 1.1|Alan Dague-Greene|400;700
Cousine|mono|OFL 1.1|Steve Matteson|400;700
Coustard|serif|OFL 1.1|Vernon Adams|400;900
Covered By Your Grace|handskrift|OFL 1.1|Kimberly Geswein|400
Crafty Girls|handskrift|Apache 2.0|Tart Workshop|400
Creepster|display|OFL 1.1|Sideshow|400
Crete Round|serif|OFL 1.1|TypeTogether|400
Crimson Pro|serif|OFL 1.1|Jacques Le Bailly|200..900
Crimson Text|serif|OFL 1.1|Sebastian Kosch|400;600;700
Croissant One|display|OFL 1.1|Eduardo Tunni|400
Crushed|display|Apache 2.0|Astigmatic|400
Cuprum|sans|OFL 1.1|Jovanny Lemonad|400..700
Cute Font|display|OFL 1.1|TypoDesign Lab. Inc|400
Cutive|serif|OFL 1.1|Vernon Adams|400
Cutive Mono|mono|OFL 1.1|Vernon Adams|400
Dai Banna SIL|serif|OFL 1.1|SIL International|300;400;500;600;700
Damion|handskrift|OFL 1.1|Vernon Adams|400
Dancing Script|handskrift|OFL 1.1|Impallari Type|400..700
Danfo|serif|OFL 1.1|Afrotype, Seyi Olusanya, Eyiyemi Adegbite, David Udoh, Mirko Velimirović|400
Dangrek|display|OFL 1.1|Danh Hong|400
Darker Grotesque|sans|OFL 1.1|Gabriel Lam, ViệtAnh Nguyễn|300..900
Darumadrop One|display|OFL 1.1|Maniackers Design|400
Datatype|mono|OFL 1.1|Frank Tisellano|100..900
David Libre|serif|OFL 1.1|Monotype Imaging Inc., SIL International, Meir Sadan|400;500;700
Dawning of a New Day|handskrift|OFL 1.1|Kimberly Geswein|400
Days One|sans|OFL 1.1|Jovanny Lemonad|400
Dekko|handskrift|OFL 1.1|Sorkin Type|400
Dela Gothic One|display|OFL 1.1|artakana|400
Delicious Handrawn|handskrift|OFL 1.1|Agung Rohmat|400
Delius|handskrift|OFL 1.1|Natalia Raices|400
Delius Swash Caps|handskrift|OFL 1.1|Natalia Raices|400
Delius Unicase|handskrift|OFL 1.1|Natalia Raices|400;700
Della Respira|serif|OFL 1.1|Nathan Willis|400
Denk One|sans|OFL 1.1|Sorkin Type|400
Devonshire|handskrift|OFL 1.1|Astigmatic|400
Dhurjati|sans|OFL 1.1|Purushoth Kumar Guttula|400
Didact Gothic|sans|OFL 1.1|Daniel Johnson, Cyreal|400
Diphylleia|serif|OFL 1.1|Minha Hyung, JAMO|400
Diplomata|display|OFL 1.1|Eduardo Tunni|400
Diplomata SC|display|OFL 1.1|Eduardo Tunni|400
DM Mono|mono|OFL 1.1|Colophon Foundry|300;400;500
DM Sans|sans|OFL 1.1|Colophon Foundry|100..1000
DM Serif Display|serif|OFL 1.1|Colophon Foundry|400
DM Serif Text|serif|OFL 1.1|Colophon Foundry|400
Do Hyeon|sans|OFL 1.1|Woowahan Brothers|400
Dokdo|display|OFL 1.1|FONTRIX|400
Domine|serif|OFL 1.1|Impallari Type|400..700
Donegal One|serif|OFL 1.1|Gary Lonergan|400
Dongle|sans|OFL 1.1|Yanghee Ryu|300;400;700
Doppio One|sans|OFL 1.1|Szymon Celej|400
Dorsa|sans|OFL 1.1|Santiago Orozco|400
Dosis|sans|OFL 1.1|Impallari Type|200..800
DotGothic16|sans|OFL 1.1|Fontworks Inc.|400
Doto|sans|OFL 1.1|Óliver Lalan|100..900
Dr Sugiyama|handskrift|OFL 1.1|Sudtipos|400
Duru Sans|sans|OFL 1.1|Onur Yazıcıgil|400
Dynalight|display|OFL 1.1|Astigmatic|400
DynaPuff|display|OFL 1.1|Toshi Omagari, Jennifer Daniel|400..700
Eagle Lake|handskrift|OFL 1.1|Astigmatic|400
East Sea Dokdo|handskrift|OFL 1.1|YoonDesign Inc|400
Eater|display|OFL 1.1|Typomondo|400
EB Garamond|serif|OFL 1.1|Georg Duffner, Octavio Pardo|400..800
Economica|sans|OFL 1.1|Vicente Lamónaca|400;700
Eczar|serif|OFL 1.1|Rosetta, Vaibhav Singh|400..800
Edu AU VIC WA NT Arrows|handskrift|OFL 1.1|Tina Anderson, Corey Anderson|400..700
Edu AU VIC WA NT Dots|handskrift|OFL 1.1|Tina Anderson, Corey Anderson|400..700
Edu AU VIC WA NT Guides|handskrift|OFL 1.1|Tina Anderson, Corey Anderson|400..700
Edu AU VIC WA NT Hand|handskrift|OFL 1.1|Tina Anderson, Corey Anderson|400..700
Edu AU VIC WA NT Pre|handskrift|OFL 1.1|Tina Anderson, Corey Anderson|400..700
Edu NSW ACT Foundation|handskrift|OFL 1.1|Tina Anderson, Corey Anderson|400..700
Edu QLD Beginner|handskrift|OFL 1.1|Tina Anderson, Corey Anderson|400..700
Edu SA Beginner|handskrift|OFL 1.1|Tina Anderson, Corey Anderson|400..700
Edu TAS Beginner|handskrift|OFL 1.1|Tina Anderson, Corey Anderson|400..700
Edu VIC WA NT Beginner|handskrift|OFL 1.1|Tina Anderson, Corey Anderson|400..700
El Messiri|sans|OFL 1.1|Mohamed Gaber, Jovanny Lemonad|400..700
Electrolize|sans|OFL 1.1|Gaslight|400
Elms Sans|sans|OFL 1.1|Amarachi Nwauwa, Gida Type Studio|100..900
Elsie|display|OFL 1.1|Alejandro Inler|400;900
Elsie Swash Caps|display|OFL 1.1|Alejandro Inler|400;900
Emblema One|display|OFL 1.1|Riccardo De Franceschi|400
Emilys Candy|display|OFL 1.1|Neapolitan|400
Encode Sans|sans|OFL 1.1|Impallari Type, Andres Torresi, Jacques Le Bailly|100..900
Encode Sans Condensed|sans|OFL 1.1|Impallari Type, Andres Torresi, Jacques Le Bailly|100;200;300;400;500;600;700;800;900
Encode Sans Expanded|sans|OFL 1.1|Impallari Type, Andres Torresi, Jacques Le Bailly|100;200;300;400;500;600;700;800;900
Encode Sans SC|sans|OFL 1.1|Impallari Type, Andres Torresi, Jacques Le Bailly|100..900
Encode Sans Semi Condensed|sans|OFL 1.1|Impallari Type, Andres Torresi, Jacques Le Bailly|100;200;300;400;500;600;700;800;900
Encode Sans Semi Expanded|sans|OFL 1.1|Impallari Type, Andres Torresi, Jacques Le Bailly|100;200;300;400;500;600;700;800;900
Engagement|handskrift|OFL 1.1|Astigmatic|400
Englebert|sans|OFL 1.1|Astigmatic|400
Enriqueta|serif|OFL 1.1|FontFuror|400;500;600;700
Ephesis|handskrift|OFL 1.1|Robert Leuschke|400
Epilogue|sans|OFL 1.1|Tyler Finck, ETC|100..900
Epunda Sans|sans|OFL 1.1|Typofactur|300..900
Epunda Slab|serif|OFL 1.1|Typofactur|300..900
Erica One|display|OFL 1.1|Miguel Hernandez|400
Esteban|serif|OFL 1.1|Angélica Díaz|400
Estedad|sans|OFL 1.1|Amin Abedi, Fontamin|100..900
Estonia|handskrift|OFL 1.1|Robert Leuschke|400
Euphoria Script|handskrift|OFL 1.1|Sabrina Mariela Lopez|400
Ewert|display|OFL 1.1|Johan Kallas, Mihkel Virkus|400
Exile|display|OFL 1.1|Bartłomiej Rózga|400
Exo|sans|OFL 1.1|Natanael Gama, Robin Mientjes|100..900
Exo 2|sans|OFL 1.1|Natanael Gama|100..900
Expletus Sans|display|OFL 1.1|Designtown|400..700
Explora|handskrift|OFL 1.1|Robert Leuschke|400
Faculty Glyphic|sans|OFL 1.1|Koto Studio|400
Fahkwang|sans|OFL 1.1|Cadson Demak|200;300;400;500;600;700
Familjen Grotesk|sans|OFL 1.1|Familjen STHLM AB|400..700
Fanwood Text|serif|OFL 1.1|Barry Schwartz|400
Farro|sans|OFL 1.1|Grayscale|300;400;500;700
Farsan|display|OFL 1.1|Pooja Saxena|400
Fascinate|display|OFL 1.1|Astigmatic|400
Fascinate Inline|display|OFL 1.1|Astigmatic|400
Faster One|display|OFL 1.1|Eduardo Tunni|400
Fasthand|display|OFL 1.1|Danh Hong, Neapolitan|400
Fauna One|serif|OFL 1.1|Eduardo Tunni|400
Faustina|serif|OFL 1.1|Omnibus-Type|300..800
Federant|display|OFL 1.1|Cyreal|400
Federo|sans|OFL 1.1|Cyreal|400
Felipa|handskrift|OFL 1.1|Fontstage|400
Fenix|serif|OFL 1.1|Fernando Díaz|400
Festive|handskrift|OFL 1.1|Robert Leuschke|400
Figtree|sans|OFL 1.1|Erik Kennedy|300..900
Finger Paint|display|OFL 1.1|Carrois Apostrophe|400
Finlandica Headline|sans|OFL 1.1|Helsinki Type Studio, Niklas Ekholm, Juho Hiilivirta, Jaakko Suomalainen|100..900
Finlandica Text|sans|OFL 1.1|Helsinki Type Studio, Niklas Ekholm, Juho Hiilivirta, Jaakko Suomalainen|100..900
Fira Code|mono|OFL 1.1|The Mozilla Foundation, Telefonica S.A., Nikita Prokopov|300..700
Fira Mono|mono|OFL 1.1|Carrois Apostrophe|400;500;700
Fira Sans|sans|OFL 1.1|Carrois Apostrophe|100;200;300;400;500;600;700;800;900
Fira Sans Condensed|sans|OFL 1.1|Carrois Apostrophe|100;200;300;400;500;600;700;800;900
Fira Sans Extra Condensed|sans|OFL 1.1|Carrois Apostrophe|100;200;300;400;500;600;700;800;900
Fjalla One|sans|OFL 1.1|Sorkin Type, Irina Smirnova|400
Fjord One|serif|OFL 1.1|Viktoriya Grabowska|400
Flamenco|display|OFL 1.1|LatinoType|300;400
Flavors|display|OFL 1.1|Sideshow|400
Fleur De Leah|handskrift|OFL 1.1|Robert Leuschke|400
Flow Block|display|OFL 1.1|Dan Ross|400
Flow Circular|display|OFL 1.1|Dan Ross|400
Flow Rounded|display|OFL 1.1|Dan Ross|400
Foldit|display|OFL 1.1|Sophia Tai|100..900
Fondamento|handskrift|OFL 1.1|Astigmatic|400
Fontdiner Swanky|display|Apache 2.0|Font Diner|400
Forum|display|OFL 1.1|Denis Masharov|400
Fragment Mono|mono|OFL 1.1|Wei Huang, URW Design Studio|400
Francois One|sans|OFL 1.1|Vernon Adams|400
Frank Ruhl Libre|serif|OFL 1.1|Yanek Iontef|300..900
Fraunces|serif|OFL 1.1|Undercase Type, Phaedra Charles, Flavia Zimbardi|100..900
Freckle Face|display|OFL 1.1|Astigmatic|400
Fredericka the Great|display|OFL 1.1|Tart Workshop|400
Fredoka|sans|OFL 1.1|Milena Brandão, Hafontia|300..700
Freehand|display|OFL 1.1|Danh Hong|400
Freeman|display|OFL 1.1|Rodrigo Fuenzalida, Aoife Mooney, Vernon Adams|400
Fresca|sans|OFL 1.1|Fontstage|400
Frijole|display|OFL 1.1|Sideshow|400
Fruktur|display|OFL 1.1|Viktoriya Grabowska, Eben Sorkin|400
Fugaz One|display|OFL 1.1|LatinoType|400
Fuggles|handskrift|OFL 1.1|Robert Leuschke|400
Funnel Display|display|OFL 1.1|NORD ID, Kristian Möller|300..800
Funnel Sans|sans|OFL 1.1|NORD ID, Kristian Möller|300..800
Fustat|sans|OFL 1.1|Mohamed Gaber, Laura Garcia Mut, Khaled Hosny|200..800
Fuzzy Bubbles|handskrift|OFL 1.1|Robert Leuschke|400;700
Ga Maamli|display|OFL 1.1|Afotey Clement Nii Odai, Ama Diaka, David Abbey-Thompson|400
Gabarito|display|OFL 1.1|Naipe Foundry, Leandro Assis, Álvaro Franca, Felipe Casaprima|400..900
Gabriela|serif|OFL 1.1|Eduardo Tunni|400
Gaegu|handskrift|OFL 1.1|JIKJI SOFT|300;400;700
Gafata|sans|OFL 1.1|Lautaro Hourcade|400
Gajraj One|display|OFL 1.1|Saurabh Sharma|400
Galada|display|OFL 1.1|Black Foundry|400
Galdeano|sans|OFL 1.1|Dario Manuel Muhafara|400
Galindo|display|OFL 1.1|Astigmatic|400
Gamja Flower|handskrift|OFL 1.1|YoonDesign Inc|400
Gantari|sans|OFL 1.1|Lafontype|100..900
Gasoek One|sans|OFL 1.1|Jiashuo Zhang, JAMO|400
Gayathri|sans|OFL 1.1|SMC, Binoy Dominic|100;400;700
Geist|sans|OFL 1.1|Andrés Briganti, Mateo Zaragoza, Guillermo Rauch, Evil Rabbit, José Rago, Facundo Santana|100..900
Geist Mono|mono|OFL 1.1|Andrés Briganti, Mateo Zaragoza, Guillermo Rauch, Evil Rabbit, José Rago, Facundo Santana|100..900
Geist Pixel|display|OFL 1.1|Andrés Briganti, Evil Rabbit, Guillermo Rauch|400
Gelasio|serif|OFL 1.1|Eben Sorkin|400..700
Gemunu Libre|sans|OFL 1.1|Mooniak|200..800
Genos|sans|OFL 1.1|Robert Leuschke|100..900
Gentium Book Plus|serif|OFL 1.1|SIL International|400;700
Gentium Plus|serif|OFL 1.1|SIL International|400;700
Geo|sans|OFL 1.1|Ben Weiner|400
Geologica|sans|OFL 1.1|Monokrom, Sindre Bremnes, Frode Helland|100..900
Geom|sans|OFL 1.1|Thanos Poulakidas|300..900
Geomini|sans|OFL 1.1|FontBob|200..800
Georama|sans|OFL 1.1|Production Type|100..900
Geostar|display|OFL 1.1|Joe Prince|400
Geostar Fill|display|OFL 1.1|Joe Prince|400
Germania One|display|OFL 1.1|John Vargas Beltrán|400
GFS Didot|serif|OFL 1.1|Greek Font Society|400
GFS Neohellenic|sans|OFL 1.1|Greek Font Society|400;700
Gideon Roman|display|OFL 1.1|Robert Leuschke|400
Gidole|sans|OFL 1.1|Andreas Larsen|400
Gidugu|sans|OFL 1.1|Purushoth Kumar Guttula|400
Gilda Display|serif|OFL 1.1|Eduardo Tunni|400
Girassol|display|OFL 1.1|Liam Spradlin|400
Give You Glory|handskrift|OFL 1.1|Kimberly Geswein|400
Glass Antiqua|display|OFL 1.1|Denis Masharov|400
Glegoo|serif|OFL 1.1|Eduardo Tunni|400;700
Gloock|serif|OFL 1.1|Duarte Pinto|400
Gloria Hallelujah|handskrift|OFL 1.1|Kimberly Geswein|400
Glory|sans|OFL 1.1|Robert Leuschke|100..800
Gluten|display|OFL 1.1|Tyler Finck, ETC|100..900
Goblin One|display|OFL 1.1|Riccardo De Franceschi|400
Gochi Hand|handskrift|OFL 1.1|HT Fonts|400
Goldman|display|OFL 1.1|Jaikishan Patel|400;700
Golos Text|sans|OFL 1.1|Alexandra Korolkova, Vitaly Kuzmin|400..900
Google Sans|sans|OFL 1.1|Google|400..700
Google Sans Code|mono|OFL 1.1|Google, Universal Thirst|300..800
Google Sans Flex|sans|OFL 1.1|Google|1..1000
Gorditas|display|OFL 1.1|Gustavo Dipre|400;700
Gothic A1|sans|OFL 1.1|HanYang I&C Co|100;200;300;400;500;600;700;800;900
Gotu|sans|OFL 1.1|Ek Type|400
Goudy Bookletter 1911|serif|OFL 1.1|Barry Schwartz|400
Gowun Batang|serif|OFL 1.1|Yanghee Ryu|400;700
Gowun Dodum|sans|OFL 1.1|Yanghee Ryu|400
Graduate|serif|OFL 1.1|Eduardo Tunni|400
Grand Hotel|handskrift|OFL 1.1|Astigmatic|400
Grandiflora One|serif|OFL 1.1|Haesung Cho, JAMO|400
Grandstander|display|OFL 1.1|Tyler Finck, ETC|100..900
Grape Nuts|handskrift|OFL 1.1|Robert Leuschke|400
Gravitas One|display|OFL 1.1|Riccardo De Franceschi|400
Great Vibes|handskrift|OFL 1.1|Robert Leuschke|400
Grechen Fuemen|handskrift|OFL 1.1|Robert Leuschke|400
Grenze|serif|OFL 1.1|Omnibus-Type|100..900
Grenze Gotisch|display|OFL 1.1|Omnibus-Type|100..900
Grey Qo|handskrift|OFL 1.1|Robert Leuschke|400
Griffy|display|OFL 1.1|Neapolitan|400
Gruppo|sans|OFL 1.1|Vernon Adams|400
Gudea|sans|OFL 1.1|Agustina Mingote|400;700
Gugi|display|OFL 1.1|TAE System & Typefaces Co.|400
Gulzar|serif|OFL 1.1|Borna Izadpanah, Fiona Ross, Alice Savoie, Simon Cozens|400
Gupter|serif|OFL 1.1|Octavio Pardo|400;500;700
Gurajada|sans|OFL 1.1|Purushoth Kumar Guttula|400
Gveret Levin|handskrift|OFL 1.1|AlefAlefAlef|400
Gwendolyn|handskrift|OFL 1.1|Robert Leuschke|400;700
Habibi|serif|OFL 1.1|Magnus Gaarde|400
Hachi Maru Pop|handskrift|OFL 1.1|Nonty|400
Hahmlet|serif|OFL 1.1|Hypertype|100..900
Halant|serif|OFL 1.1|Indian Type Foundry|300;400;500;600;700
Hammersmith One|sans|OFL 1.1|Nicole Fally|400
Hanalei|display|OFL 1.1|Astigmatic|400
Hanalei Fill|display|OFL 1.1|Astigmatic|400
Handjet|display|OFL 1.1|Rosetta, David Březina|100..900
Handlee|handskrift|OFL 1.1|Joe Prince|400
Hanken Grotesk|sans|OFL 1.1|Alfredo Marco Pradil, Hanken Design Co.|100..900
Hanuman|serif|OFL 1.1|Danh Hong|100..900
Happy Monkey|display|OFL 1.1|Brenda Gallo|400
Harmattan|sans|OFL 1.1|SIL International|400;500;600;700
Headland One|serif|OFL 1.1|Gary Lonergan|400
Hedvig Letters Sans|sans|OFL 1.1|Kanon Foundry, Alexander Örn, Tor Weibull, Hedvig|400
Hedvig Letters Serif|serif|OFL 1.1|Kanon Foundry, Alexander Örn, Tor Weibull, Hedvig|400
Heebo|sans|OFL 1.1|Oded Ezer|100..900
Henny Penny|display|OFL 1.1|Brownfox|400
Hepta Slab|serif|OFL 1.1|Mike LaGattuta|1..900
Herr Von Muellerhoff|handskrift|OFL 1.1|Sudtipos|400
Hi Melody|handskrift|OFL 1.1|YoonDesign Inc|400
Hibur Mono|mono|OFL 1.1|TypeHabesha, Behailu Berento|400
Hina Mincho|serif|OFL 1.1|Satsuyako|400
Hind|sans|OFL 1.1|Indian Type Foundry|300;400;500;600;700
Hind Guntur|sans|OFL 1.1|Indian Type Foundry|300;400;500;600;700
Hind Madurai|sans|OFL 1.1|Indian Type Foundry|300;400;500;600;700
Hind Mysuru|sans|OFL 1.1|Indian Type Foundry|300;400;500;600;700
Hind Siliguri|sans|OFL 1.1|Indian Type Foundry|300;400;500;600;700
Hind Vadodara|sans|OFL 1.1|Indian Type Foundry|300;400;500;600;700
Holtwood One SC|serif|OFL 1.1|Vernon Adams|400
Homemade Apple|handskrift|Apache 2.0|Font Diner|400
Homenaje|sans|OFL 1.1|Constanza Artigas Preller, Agustina Mingote|400
Honk|display|OFL 1.1|Ek Type|400
Host Grotesk|sans|OFL 1.1|Element Type, Doğukan Karapınar, İbrahim Kaçtıoğlu|300..800
Hubballi|sans|OFL 1.1|Erin McLaughlin|400
Hubot Sans|sans|OFL 1.1|Tobias Bjerrome Ahlin, Github, Degarism Studio, Sebastian Carewe|200..900
Huninn|sans|OFL 1.1|justfont|400
Hurricane|handskrift|OFL 1.1|Robert Leuschke|400
Iansui|handskrift|OFL 1.1|But Ko|400
Ibarra Real Nova|serif|OFL 1.1|José María Ribagorda, Octavio Pardo|400..700
IBM Plex Mono|mono|OFL 1.1|Mike Abbink, Bold Monday|100;200;300;400;500;600;700
IBM Plex Sans|sans|OFL 1.1|Mike Abbink, Bold Monday|100..700
IBM Plex Sans Arabic|sans|OFL 1.1|Mike Abbink, Bold Monday, Khajag Apelian, Wael Morcos|100;200;300;400;500;600;700
IBM Plex Sans Condensed|sans|OFL 1.1|Mike Abbink, Bold Monday|100;200;300;400;500;600;700
IBM Plex Sans Devanagari|sans|OFL 1.1|Mike Abbink, Bold Monday|100;200;300;400;500;600;700
IBM Plex Sans Hebrew|sans|OFL 1.1|Mike Abbink, Bold Monday|100;200;300;400;500;600;700
IBM Plex Sans JP|sans|OFL 1.1|Mike Abbink, Bold Monday|100;200;300;400;500;600;700
IBM Plex Sans KR|sans|OFL 1.1|Mike Abbink, Bold Monday|100;200;300;400;500;600;700
IBM Plex Sans Thai|sans|OFL 1.1|Mike Abbink, Bold Monday|100;200;300;400;500;600;700
IBM Plex Sans Thai Looped|sans|OFL 1.1|Mike Abbink, Bold Monday|100;200;300;400;500;600;700
IBM Plex Serif|serif|OFL 1.1|Mike Abbink, Bold Monday|100;200;300;400;500;600;700
Iceberg|display|OFL 1.1|Cyreal|400
Iceland|display|OFL 1.1|Cyreal|400
Idiqlat|serif|OFL 1.1|SIL International|200;300;400
IM Fell Double Pica|serif|OFL 1.1|Igino Marini|400
IM Fell Double Pica SC|serif|OFL 1.1|Igino Marini|400
IM Fell DW Pica|serif|OFL 1.1|Igino Marini|400
IM Fell DW Pica SC|serif|OFL 1.1|Igino Marini|400
IM Fell English|serif|OFL 1.1|Igino Marini|400
IM Fell English SC|serif|OFL 1.1|Igino Marini|400
IM Fell French Canon|serif|OFL 1.1|Igino Marini|400
IM Fell French Canon SC|serif|OFL 1.1|Igino Marini|400
IM Fell Great Primer|serif|OFL 1.1|Igino Marini|400
IM Fell Great Primer SC|serif|OFL 1.1|Igino Marini|400
Imbue|serif|OFL 1.1|Tyler Finck, ETC|100..900
Imperial Script|handskrift|OFL 1.1|Robert Leuschke|400
Imprima|sans|OFL 1.1|Eduardo Tunni|400
Inclusive Sans|sans|OFL 1.1|Olivia King|300..700
Inconsolata|mono|OFL 1.1|Raph Levien|200..900
Inder|sans|OFL 1.1|Sorkin Type|400
Indie Flower|handskrift|OFL 1.1|Kimberly Geswein|400
Ingrid Darling|handskrift|OFL 1.1|Robert Leuschke|400
Inika|serif|OFL 1.1|Constanza Artigas|400;700
Inknut Antiqua|serif|OFL 1.1|Claus Eggers Sørensen|300;400;500;600;700;800;900
Inria Sans|sans|OFL 1.1|Grégori Vincens, Jérémie Hornus|300;400;700
Inria Serif|serif|OFL 1.1|Grégori Vincens, Jérémie Hornus|300;400;700
Inspiration|handskrift|OFL 1.1|Robert Leuschke|400
Instrument Sans|sans|OFL 1.1|Rodrigo Fuenzalida, Jordan Egstad|400..700
Instrument Serif|serif|OFL 1.1|Rodrigo Fuenzalida, Jordan Egstad|400
Intel One Mono|mono|OFL 1.1|Intel Corporation, Frere-Jones Type|300..700
Inter|sans|OFL 1.1|Rasmus Andersson|100..900
Inter Tight|sans|OFL 1.1|Rasmus Andersson|100..900
Iosevka Charon|mono|OFL 1.1|Juliette Pluto|300;400;500;700
Iosevka Charon Mono|mono|OFL 1.1|Juliette Pluto|300;400;500;700
Irish Grover|display|Apache 2.0|Sideshow|400
Island Moments|handskrift|OFL 1.1|Robert Leuschke|400
Istok Web|sans|OFL 1.1|Andrey V. Panov|400;700
Italiana|sans|OFL 1.1|Santiago Orozco|400
Italianno|handskrift|OFL 1.1|Robert Leuschke|400
Itim|handskrift|OFL 1.1|Cadson Demak|400
Jacquard 12|display|OFL 1.1|Sarah Cadigan-Fried|400
Jacquard 12 Charted|display|OFL 1.1|Sarah Cadigan-Fried|400
Jacquard 24|display|OFL 1.1|Sarah Cadigan-Fried|400
Jacquard 24 Charted|display|OFL 1.1|Sarah Cadigan-Fried|400
Jacquarda Bastarda 9|display|OFL 1.1|Sarah Cadigan-Fried|400
Jacquarda Bastarda 9 Charted|display|OFL 1.1|Sarah Cadigan-Fried|400
Jacques Francois|serif|OFL 1.1|Cyreal|400
Jacques Francois Shadow|display|OFL 1.1|Cyreal|400
Jaini|display|OFL 1.1|Ek Type|400
Jaini Purva|display|OFL 1.1|Ek Type|400
Jaldi|sans|OFL 1.1|Omnibus-Type|400;700
Jaro|sans|OFL 1.1|Agyei Archer, Céline Hurka, Mirko Velimirović|400
Jersey 10|display|OFL 1.1|Sarah Cadigan-Fried|400
Jersey 10 Charted|display|OFL 1.1|Sarah Cadigan-Fried|400
Jersey 15|display|OFL 1.1|Sarah Cadigan-Fried|400
Jersey 15 Charted|display|OFL 1.1|Sarah Cadigan-Fried|400
Jersey 20|display|OFL 1.1|Sarah Cadigan-Fried|400
Jersey 20 Charted|display|OFL 1.1|Sarah Cadigan-Fried|400
Jersey 25|display|OFL 1.1|Sarah Cadigan-Fried|400
Jersey 25 Charted|display|OFL 1.1|Sarah Cadigan-Fried|400
JetBrains Mono|mono|OFL 1.1|JetBrains, Philipp Nurullin, Konstantin Bulenkov|100..800
Jim Nightshade|handskrift|OFL 1.1|Astigmatic|400
Joan|serif|OFL 1.1|Paolo Biagini|400
Jockey One|sans|OFL 1.1|TypeTogether|400
Jolly Lodger|display|OFL 1.1|Font Diner|400
Jomhuria|display|OFL 1.1|KB Studio|400
Jomolhari|serif|OFL 1.1|Christopher J. Fynn|400
Josefin Sans|sans|OFL 1.1|Santiago Orozco|100..700
Josefin Slab|serif|OFL 1.1|Santiago Orozco|100..700
Jost|sans|OFL 1.1|Owen Earl|100..900
Joti One|display|OFL 1.1|Eduardo Tunni|400
Jua|sans|OFL 1.1|Woowahan Brothers|400
Judson|serif|OFL 1.1|Daniel Johnson|400;700
Julee|handskrift|OFL 1.1|Julián Tunni|400
Julius Sans One|sans|OFL 1.1|Luciano Vergara|400
Junge|serif|OFL 1.1|Cyreal|400
Jura|sans|OFL 1.1|Daniel Johnson, Cyreal|300..700
Just Another Hand|handskrift|Apache 2.0|Astigmatic|400
Just Me Again Down Here|handskrift|OFL 1.1|Kimberly Geswein|400
K2D|sans|OFL 1.1|Cadson Demak|100;200;300;400;500;600;700;800
Kablammo|display|OFL 1.1|Vectro Type Foundry, Travis Kochel, Lizy Gershenzon, Daria Cohen, Ethan Cohen|400
Kadwa|serif|OFL 1.1|Sol Matas|400;700
Kaisei Decol|serif|OFL 1.1|Font-Kai|400;500;700
Kaisei HarunoUmi|serif|OFL 1.1|Font-Kai|400;500;700
Kaisei Opti|serif|OFL 1.1|Font-Kai|400;500;700
Kaisei Tokumin|serif|OFL 1.1|Font-Kai|400;500;700;800
Kalam|handskrift|OFL 1.1|Indian Type Foundry|300;400;700
Kalnia|serif|OFL 1.1|Frida Medrano|100..700
Kalnia Glaze|display|OFL 1.1|Frida Medrano|100..700
Kameron|serif|OFL 1.1|Vernon Adams|400..700
Kanchenjunga|sans|OFL 1.1|Becca Hirsbrunner Spalinger|400;500;600;700
Kanit|sans|OFL 1.1|Cadson Demak|100;200;300;400;500;600;700;800;900
Kantumruy Pro|sans|OFL 1.1|Tep Sovichet, Wei Huang|100..700
Kapakana|handskrift|OFL 1.1|Kousuke Nagai|300..400
Karantina|display|OFL 1.1|Rony Koch|300;400;700
Karla|sans|OFL 1.1|Jonny Pinhorn|200..800
Karma|serif|OFL 1.1|Indian Type Foundry|300;400;500;600;700
Katibeh|display|OFL 1.1|KB Studio|400
Kaushan Script|handskrift|OFL 1.1|Impallari Type|400
Kavivanar|handskrift|OFL 1.1|Tharique Azeez|400
Kavoon|display|OFL 1.1|Viktoriya Grabowska|400
Kay Pho Du|serif|OFL 1.1|SIL International|400;500;600;700
Kdam Thmor Pro|sans|OFL 1.1|Tep Sovichet, Hak Longdey|400
Keania One|display|OFL 1.1|Julia Petretta|400
Kedebideri|sans|OFL 1.1|SIL International|400;500;600;700;800;900
Kelly Slab|display|OFL 1.1|Denis Masharov|400
Kenia|display|OFL 1.1|Julia Petretta|400
Khand|sans|OFL 1.1|Indian Type Foundry|300;400;500;600;700
Khula|sans|OFL 1.1|Erin McLaughlin|300;400;600;700;800
Kings|handskrift|OFL 1.1|Robert Leuschke|400
Kirang Haerang|display|OFL 1.1|Woowahan Brothers|400
Kite One|sans|OFL 1.1|Eduardo Tunni|400
Kiwi Maru|serif|OFL 1.1|Hiroki-Chan|300;400;500
Klee One|handskrift|OFL 1.1|Fontworks Inc.|400;600
Knewave|display|OFL 1.1|Tyler Finck|400
Kodchasan|sans|OFL 1.1|Cadson Demak|200;300;400;500;600;700
Kode Mono|mono|OFL 1.1|Isa Ozler|400..700
Koh Santepheap|serif|OFL 1.1|Danh Hong|100;300;400;700;900
KoHo|sans|OFL 1.1|Cadson Demak|200;300;400;500;600;700
Kolker Brush|handskrift|OFL 1.1|Robert Leuschke|400
Konkhmer Sleokchher|display|OFL 1.1|Suon May Sophanith|400
Kosugi|sans|Apache 2.0|MOTOYA|400
Kosugi Maru|sans|Apache 2.0|MOTOYA|400
Kotta One|serif|OFL 1.1|Ania Kruk|400
Koulen|display|OFL 1.1|Danh Hong|400
Kranky|display|Apache 2.0|Sideshow|400
Kreon|serif|OFL 1.1|Julia Petretta|300..700
Kristi|handskrift|OFL 1.1|Birgit Pulk|400
Krona One|sans|OFL 1.1|Yvonne Schüttler|400
Krub|sans|OFL 1.1|Cadson Demak|200;300;400;500;600;700
Kufam|sans|OFL 1.1|Original Type, Wael Morcos, Artur Schmal|400..900
Kulim Park|sans|OFL 1.1|Dale Sattler|200;300;400;600;700
Kumar One|display|OFL 1.1|Indian Type Foundry|400
Kumar One Outline|display|OFL 1.1|Indian Type Foundry|400
Kumbh Sans|sans|OFL 1.1|Saurabh Sharma|100..900
Kurale|serif|OFL 1.1|Eduardo Tunni|400
La Belle Aurore|handskrift|OFL 1.1|Kimberly Geswein|400
Labrada|serif|OFL 1.1|Mercedes Jáuregui, Omnibus-Type|100..900
Lacquer|display|OFL 1.1|Niki Polyocan, Eli Block|400
Laila|serif|OFL 1.1|Indian Type Foundry|300;400;500;600;700
Lakki Reddy|handskrift|OFL 1.1|Appaji Ambarisha Darbha|400
Lalezar|sans|OFL 1.1|Borna Izadpanah|400
Lancelot|display|OFL 1.1|Marion Kadi|400
Langar|display|OFL 1.1|Typeland, Alessia Mazzarella|400
Lateef|serif|OFL 1.1|SIL International|200;300;400;500;600;700;800
Lato|sans|OFL 1.1|Łukasz Dziedzic|100;300;400;700;900
Lavishly Yours|handskrift|OFL 1.1|Robert Leuschke|400
League Gothic|sans|OFL 1.1|Tyler Finck, Caroline Hadilaksono, Micah Rich|400
League Script|handskrift|OFL 1.1|Haley Fiege|400
League Spartan|sans|OFL 1.1|Matt Bailey, Tyler Finck|100..900
Leckerli One|handskrift|OFL 1.1|Gesine Todt|400
Ledger|serif|OFL 1.1|Denis Masharov|400
Lekton|mono|OFL 1.1|ISIA Urbino|400;700
Lemon|display|OFL 1.1|Eduardo Tunni|400
Lemonada|display|OFL 1.1|Mohamed Gaber, Eduardo Tunni|300..700
Lexend|sans|OFL 1.1|Bonnie Shaver-Troup, Thomas Jockin, Santiago Orozco, Héctor Gómez, Superunion|100..900
Lexend Deca|sans|OFL 1.1|Bonnie Shaver-Troup, Thomas Jockin, Santiago Orozco, Héctor Gómez, Superunion|100..900
Lexend Exa|sans|OFL 1.1|Bonnie Shaver-Troup, Thomas Jockin, Santiago Orozco, Héctor Gómez, Superunion|100..900
Lexend Giga|sans|OFL 1.1|Bonnie Shaver-Troup, Thomas Jockin, Santiago Orozco, Héctor Gómez, Superunion|100..900
Lexend Mega|sans|OFL 1.1|Bonnie Shaver-Troup, Thomas Jockin, Santiago Orozco, Héctor Gómez, Superunion|100..900
Lexend Peta|sans|OFL 1.1|Bonnie Shaver-Troup, Thomas Jockin, Santiago Orozco, Héctor Gómez, Superunion|100..900
Lexend Tera|sans|OFL 1.1|Bonnie Shaver-Troup, Thomas Jockin, Santiago Orozco, Héctor Gómez, Superunion|100..900
Lexend Zetta|sans|OFL 1.1|Bonnie Shaver-Troup, Thomas Jockin, Santiago Orozco, Héctor Gómez, Superunion|100..900
Libertinus Keyboard|display|OFL 1.1|Philipp H. Poll|400
Libertinus Mono|mono|OFL 1.1|Philipp H. Poll|400
Libertinus Sans|sans|OFL 1.1|Philipp H. Poll|400;700
Libertinus Serif|serif|OFL 1.1|Philipp H. Poll|400;600;700
Libertinus Serif Display|display|OFL 1.1|Philipp H. Poll|400
Libre Barcode 128|display|OFL 1.1|Lasse Fister|400
Libre Barcode 128 Text|display|OFL 1.1|Lasse Fister|400
Libre Barcode 39|display|OFL 1.1|Lasse Fister|400
Libre Barcode 39 Extended|display|OFL 1.1|Lasse Fister|400
Libre Barcode 39 Extended Text|display|OFL 1.1|Lasse Fister|400
Libre Barcode 39 Text|display|OFL 1.1|Lasse Fister|400
Libre Barcode EAN13 Text|display|OFL 1.1|Lasse Fister|400
Libre Baskerville|serif|OFL 1.1|Impallari Type|400..700
Libre Bodoni|serif|OFL 1.1|Pablo Impallari, Rodrigo Fuenzalida|400..700
Libre Caslon Display|serif|OFL 1.1|Impallari Type|400
Libre Caslon Text|serif|OFL 1.1|Impallari Type|400;700
Libre Franklin|sans|OFL 1.1|Impallari Type|100..900
Licorice|handskrift|OFL 1.1|Robert Leuschke|400
Life Savers|display|OFL 1.1|Impallari Type|400;700;800
Lilex|mono|OFL 1.1|Mike Abbink, Paul van der Laan, Pieter van Rosmalen, Mikhael Khrustik|100..700
Lilita One|display|OFL 1.1|Juan Montoreano|400
Lily Script One|display|OFL 1.1|Julia Petretta|400
Limelight|display|OFL 1.1|Nicole Fally, Sorkin Type|400
Linden Hill|serif|OFL 1.1|Barry Schwartz|400
LINE Seed JP|sans|OFL 1.1|LY Corporation, RixFont, Fontworks|100;400;700;800
Lisu Bosa|serif|OFL 1.1|SIL International|200;300;400;500;600;700;800;900
Liter|sans|OFL 1.1|Anton Skugarov, Alexandr Ivanin|400
Literata|serif|OFL 1.1|TypeTogether|200..900
Liu Jian Mao Cao|handskrift|OFL 1.1|Liu Zhengjiang, Kimberly Geswein, ZhongQi|400
Livvic|sans|OFL 1.1|LV=, Jacques Le Bailly|100;200;300;400;500;600;700;900
Lobster|display|OFL 1.1|Impallari Type|400
Lobster Two|display|OFL 1.1|Impallari Type|400;700
Londrina Outline|display|OFL 1.1|Marcelo Magalhães|400
Londrina Shadow|display|OFL 1.1|Marcelo Magalhães|400
Londrina Sketch|display|OFL 1.1|Marcelo Magalhães|400
Londrina Solid|display|OFL 1.1|Marcelo Magalhães|100;300;400;900
Long Cang|handskrift|OFL 1.1|Chen Xiaomin|400
Lora|serif|OFL 1.1|Cyreal|400..700
Love Light|handskrift|OFL 1.1|Robert Leuschke|400
Love Ya Like A Sister|display|OFL 1.1|Kimberly Geswein|400
Loved by the King|handskrift|OFL 1.1|Kimberly Geswein|400
Lovers Quarrel|handskrift|OFL 1.1|Robert Leuschke|400
Luckiest Guy|display|Apache 2.0|Astigmatic|400
Lugrasimo|handskrift|OFL 1.1|The DocRepair Project, Astigmatic|400
Lumanosimo|handskrift|OFL 1.1|The DocRepair Project, Eduardo Tunni|400
Lunasima|sans|OFL 1.1|The DocRepair Project, Google|400;700
Lusitana|serif|OFL 1.1|Ana Paula Megda|400;700
Lustria|serif|OFL 1.1|MADType|400
Luxurious Roman|display|OFL 1.1|Robert Leuschke|400
Luxurious Script|handskrift|OFL 1.1|Robert Leuschke|400
LXGW Marker Gothic|sans|OFL 1.1|LXGW|400
LXGW WenKai Mono TC|mono|OFL 1.1|LXGW|300;400;700
LXGW WenKai TC|handskrift|OFL 1.1|LXGW|300;400;700
M PLUS 1|sans|OFL 1.1|Coji Morishita|100..900
M PLUS 1 Code|mono|OFL 1.1|Coji Morishita|100..700
M PLUS 1p|sans|OFL 1.1|Coji Morishita, M+ Fonts Project|100;300;400;500;700;800;900
M PLUS 2|sans|OFL 1.1|Coji Morishita|100..900
M PLUS Code Latin|sans|OFL 1.1|Coji Morishita|100..700
M PLUS Rounded 1c|sans|OFL 1.1|Coji Morishita, M+ Fonts Project|100;300;400;500;700;800;900
M PLUS U|sans|OFL 1.1|Coji Morishita|100..900
Ma Shan Zheng|handskrift|OFL 1.1|Ma ShanZheng|400
Macondo|display|OFL 1.1|John Vargas Beltrán|400
Macondo Swash Caps|display|OFL 1.1|John Vargas Beltrán|400
Mada|sans|OFL 1.1|Khaled Hosny, Paul D. Hunt|200..900
Madimi One|sans|OFL 1.1|Taurai Valerie Mtake, Mirko Velimirović|400
Magra|sans|OFL 1.1|FontFuror|400;700
Maiden Orange|serif|Apache 2.0|Astigmatic|400
Maitree|serif|OFL 1.1|Cadson Demak|200;300;400;500;600;700
Major Mono Display|mono|OFL 1.1|Emre Parlak|400
Mako|sans|OFL 1.1|Vernon Adams|400
Mali|handskrift|OFL 1.1|Cadson Demak|200;300;400;500;600;700
Mallanna|sans|OFL 1.1|Purushoth Kumar Guttula|400
Maname|serif|OFL 1.1|Pathum Egodawatta, Mooniak|400
Mandali|sans|OFL 1.1|Purushoth Kumar Guttula|400
Manjari|sans|OFL 1.1|Santhosh Thottingal|100;400;700
Manrope|sans|OFL 1.1|Mikhail Sharanda|200..800
Mansalva|handskrift|OFL 1.1|Carolina Short|400
Manuale|serif|OFL 1.1|Omnibus-Type|300..800
Manufacturing Consent|display|OFL 1.1|Fredrick Brennan|400
Marcellus|serif|OFL 1.1|Astigmatic|400
Marcellus SC|serif|OFL 1.1|Astigmatic|400
Marck Script|handskrift|OFL 1.1|Denis Masharov|400
Margarine|display|OFL 1.1|Astigmatic|400
Marhey|display|OFL 1.1|Nur Syamsi, Bustanul Arifin|300..700
Markazi Text|serif|OFL 1.1|Borna Izadpanah, Florian Runge, Fiona Ross|400..700
Marko One|serif|OFL 1.1|Cyreal|400
Marmelad|sans|OFL 1.1|Cyreal, Manvel Shmavonyan|400
Martel|serif|OFL 1.1|Dan Reynolds|200;300;400;600;700;800;900
Martel Sans|sans|OFL 1.1|Dan Reynolds, Mathieu Réguer|200;300;400;600;700;800;900
Martian Mono|mono|OFL 1.1|Roman Shamin, Evil Martians|100..800
Marvel|sans|OFL 1.1|Carolina Trebol|400;700
Matangi|sans|OFL 1.1|The Graphic Ant|300..900
Mate|serif|OFL 1.1|Eduardo Tunni|400
Mate SC|serif|OFL 1.1|Eduardo Tunni|400
Matemasie|sans|OFL 1.1|Adam Yeo|400
Maven Pro|sans|OFL 1.1|Joe Prince|400..900
McLaren|display|OFL 1.1|Astigmatic|400
Mea Culpa|handskrift|OFL 1.1|Robert Leuschke|400
Meddon|handskrift|OFL 1.1|Vernon Adams|400
MedievalSharp|display|OFL 1.1|Wojciech Kalinowski|400
Medula One|display|OFL 1.1|LatinoType|400
Meera Inimai|sans|OFL 1.1|SMC|400
Megrim|display|OFL 1.1|Daniel Johnson|400
Meie Script|handskrift|OFL 1.1|Johan Kallas, Mihkel Virkus|400
Menbere|sans|OFL 1.1|Aleme Tadesse, Sorkin Type, Eben Sorkin|100..700
Meow Script|handskrift|OFL 1.1|Robert Leuschke|400
Merienda|handskrift|OFL 1.1|Eduardo Tunni|300..900
Merriweather|serif|OFL 1.1|Sorkin Type|300..900
Merriweather Sans|sans|OFL 1.1|Sorkin Type|300..800
Metal|display|OFL 1.1|Danh Hong|400
Metal Mania|display|OFL 1.1|Open Window|400
Metamorphous|display|OFL 1.1|James Grieshaber|400
Metrophobic|sans|OFL 1.1|Vernon Adams|400
Michroma|sans|OFL 1.1|Vernon Adams|400
Micro 5|display|OFL 1.1|Sarah Cadigan-Fried|400
Micro 5 Charted|display|OFL 1.1|Sarah Cadigan-Fried|400
Milonga|display|OFL 1.1|Impallari Type|400
Miltonian|display|OFL 1.1|Impallari Type|400
Miltonian Tattoo|display|OFL 1.1|Impallari Type|400
Mina|sans|OFL 1.1|Suman Bhandary, Natanael Gama, Mooniak|400;700
Mingzat|sans|OFL 1.1|SIL International|400
Miniver|display|OFL 1.1|Open Window|400
Miranda Sans|sans|OFL 1.1|Max Thunberg|400..700
Miriam Libre|sans|OFL 1.1|Michal Sahar|400..700
Mirza|serif|OFL 1.1|KB Studio|400;500;600;700
Miss Fajardose|handskrift|OFL 1.1|Sudtipos|400
Mitr|sans|OFL 1.1|Cadson Demak|200;300;400;500;600;700
Mochiy Pop One|sans|OFL 1.1|FONTDASU|400
Mochiy Pop P One|sans|OFL 1.1|FONTDASU|400
Modak|display|OFL 1.1|Ek Type|400
Modern Antiqua|display|OFL 1.1|Wojciech Kalinowski|400
Moderustic|sans|OFL 1.1|Tural Alisoy|300..800
Mogra|display|OFL 1.1|Lipi Raval|400
Mohave|sans|OFL 1.1|Gumpita Rahayu|300..700
Moirai One|display|OFL 1.1|Jiyeon Park, JAMO|400
Molengo|sans|OFL 1.1|Denis Jacquerye|400
Momo Signature|sans|OFL 1.1|Type Associates|400
Momo Trust Display|sans|OFL 1.1|Type Associates|400
Momo Trust Sans|sans|OFL 1.1|Type Associates|200..800
Mona Sans|sans|OFL 1.1|Tobias Bjerrome Ahlin, Github, Degarism Studio, Sebastian Carewe|200..900
Monda|sans|OFL 1.1|Vernon Adams|400..700
Monofett|mono|OFL 1.1|Vernon Adams|400
Monomakh|display|OFL 1.1|Aleksandr Andreev, Nikita Simmons|400
Monomaniac One|sans|OFL 1.1|Maniackers Design|400
Monoton|display|OFL 1.1|Vernon Adams|400
Monsieur La Doulaise|handskrift|OFL 1.1|Sudtipos|400
Montaga|serif|OFL 1.1|Alejandra Rodriguez|400
Montagu Slab|serif|OFL 1.1|Florian Karsten|100..700
MonteCarlo|handskrift|OFL 1.1|Robert Leuschke|400
Montenegrin Gothic One|serif|OFL 1.1|Žarko Banović|400
Montez|handskrift|Apache 2.0|Astigmatic|400
Montserrat|sans|OFL 1.1|Julieta Ulanovsky, Sol Matas, Juan Pablo del Peral, Jacques Le Bailly|100..900
Montserrat Alternates|sans|OFL 1.1|Julieta Ulanovsky, Sol Matas, Juan Pablo del Peral, Jacques Le Bailly|100;200;300;400;500;600;700;800;900
Montserrat Underline|sans|OFL 1.1|Julieta Ulanovsky, Sol Matas, Juan Pablo del Peral, Jacques Le Bailly|100..900
Moo Lah Lah|display|OFL 1.1|Robert Leuschke|400
Mooli|sans|OFL 1.1|Vernon Adams|400
Moon Dance|handskrift|OFL 1.1|Robert Leuschke|400
Moul|display|OFL 1.1|Danh Hong|400
Moulpali|sans|OFL 1.1|Danh Hong|400
Mountains of Christmas|display|Apache 2.0|Tart Workshop|400;700
Mouse Memoirs|sans|OFL 1.1|Astigmatic|400
Mozilla Headline|sans|OFL 1.1|Studio DRAMA|200..700
Mozilla Text|sans|OFL 1.1|Studio DRAMA|200..700
Mr Bedfort|handskrift|OFL 1.1|Sudtipos|400
Mr Dafoe|handskrift|OFL 1.1|Sudtipos|400
Mr De Haviland|handskrift|OFL 1.1|Sudtipos|400
Mrs Saint Delafield|handskrift|OFL 1.1|Sudtipos|400
Mrs Sheppards|handskrift|OFL 1.1|Sudtipos|400
Ms Madi|handskrift|OFL 1.1|Robert Leuschke|400
Mukta|sans|OFL 1.1|Ek Type|200;300;400;500;600;700;800
Mukta Mahee|sans|OFL 1.1|Ek Type|200;300;400;500;600;700;800
Mukta Malar|sans|OFL 1.1|Ek Type|200;300;400;500;600;700;800
Mukta Vaani|sans|OFL 1.1|Ek Type|200;300;400;500;600;700;800
Mulish|sans|OFL 1.1|Vernon Adams, Cyreal, Jacques Le Bailly|200..1000
Murecho|sans|OFL 1.1|Neil Summerour|100..900
MuseoModerno|display|OFL 1.1|Omnibus-Type|100..900
My Soul|handskrift|OFL 1.1|Robert Leuschke|400
Mynerve|handskrift|OFL 1.1|Carolina Short|400
Mystery Quest|display|OFL 1.1|Sideshow|400
Nabla|display|OFL 1.1|Arthur Reinders Folmer, Just van Rossum|400
Namdhinggo|serif|OFL 1.1|SIL International|400;500;600;700;800
Nanum Brush Script|handskrift|OFL 1.1|Sandoll Communication|400
Nanum Gothic|sans|OFL 1.1|Sandoll Communication|400;700;800
Nanum Gothic Coding|handskrift|OFL 1.1|Sandoll Communication|400;700
Nanum Myeongjo|serif|OFL 1.1|Sandoll Communication|400;700;800
Nanum Pen Script|handskrift|OFL 1.1|Sandoll Communication|400
Narnoor|sans|OFL 1.1|SIL International|400;500;600;700;800
Nata Sans|sans|OFL 1.1|Daniel Uzquiano|100..900
National Park|sans|OFL 1.1|Andrea Herstowski, Ben Hoepner, Jeremy Shellhorn|200..800
Neonderthaw|handskrift|OFL 1.1|Robert Leuschke|400
Nerko One|handskrift|OFL 1.1|Nermin Kahrimanovic|400
Neucha|handskrift|OFL 1.1|Jovanny Lemonad|400
Neuton|serif|OFL 1.1|Brian Zick|200;300;400;700;800
New Amsterdam|sans|OFL 1.1|Vladimir Nikolic|400
New Rocker|display|OFL 1.1|Impallari Type|400
New Tegomin|serif|OFL 1.1|Kousuke Nagai|400
News Cycle|sans|OFL 1.1|Nathan Willis|400;700
Newsreader|serif|OFL 1.1|Production Type|200..800
Niconne|handskrift|OFL 1.1|Vernon Adams|400
Niramit|sans|OFL 1.1|Cadson Demak|200;300;400;500;600;700
Nixie One|display|OFL 1.1|Jovanny Lemonad|400
Nobile|sans|OFL 1.1|Vernon Adams|400;500;700
Nokora|sans|OFL 1.1|Danh Hong|100..900
Norican|handskrift|OFL 1.1|Vernon Adams|400
Nosifer|display|OFL 1.1|Typomondo|400
Notable|sans|OFL 1.1|Eli Block, Hana Tanimura, Noemie Le Coz|400
Nothing You Could Do|handskrift|OFL 1.1|Kimberly Geswein|400
Noticia Text|serif|OFL 1.1|JM Solé|400;700
Noto Kufi Arabic|sans|OFL 1.1|Google|100..900
Noto Music|sans|OFL 1.1|Google|400
Noto Naskh Arabic|serif|OFL 1.1|Google|400..700
Noto Nastaliq Urdu|serif|OFL 1.1|Google|400..700
Noto Rashi Hebrew|serif|OFL 1.1|Google|100..900
Noto Sans|sans|OFL 1.1|Google|100..900
Noto Sans Adlam|sans|OFL 1.1|Google|400..700
Noto Sans Adlam Unjoined|sans|OFL 1.1|Google|400..700
Noto Sans Anatolian Hieroglyphs|sans|OFL 1.1|Google|400
Noto Sans Arabic|sans|OFL 1.1|Google|100..900
Noto Sans Armenian|sans|OFL 1.1|Google|100..900
Noto Sans Avestan|sans|OFL 1.1|Google|400
Noto Sans Balinese|sans|OFL 1.1|Google|400..700
Noto Sans Bamum|sans|OFL 1.1|Google|400..700
Noto Sans Bassa Vah|sans|OFL 1.1|Google|400..700
Noto Sans Batak|sans|OFL 1.1|Google|400
Noto Sans Bengali|sans|OFL 1.1|Google|100..900
Noto Sans Bhaiksuki|sans|OFL 1.1|Google|400
Noto Sans Brahmi|sans|OFL 1.1|Google|400
Noto Sans Buginese|sans|OFL 1.1|Google|400
Noto Sans Buhid|sans|OFL 1.1|Google|400
Noto Sans Canadian Aboriginal|sans|OFL 1.1|Google|100..900
Noto Sans Carian|sans|OFL 1.1|Google|400
Noto Sans Caucasian Albanian|sans|OFL 1.1|Google|400
Noto Sans Chakma|sans|OFL 1.1|Google|400
Noto Sans Cham|sans|OFL 1.1|Google|100..900
Noto Sans Cherokee|sans|OFL 1.1|Google|100..900
Noto Sans Chorasmian|sans|OFL 1.1|Google|400
Noto Sans Coptic|sans|OFL 1.1|Google|400
Noto Sans Cuneiform|sans|OFL 1.1|Google|400
Noto Sans Cypriot|sans|OFL 1.1|Google|400
Noto Sans Cypro Minoan|sans|OFL 1.1|Google|400
Noto Sans Deseret|sans|OFL 1.1|Google|400
Noto Sans Devanagari|sans|OFL 1.1|Google|100..900
Noto Sans Display|sans|OFL 1.1|Google|100..900
Noto Sans Duployan|sans|OFL 1.1|Google|400;700
Noto Sans Egyptian Hieroglyphs|sans|OFL 1.1|Google|400
Noto Sans Elbasan|sans|OFL 1.1|Google|400
Noto Sans Elymaic|sans|OFL 1.1|Google|400
Noto Sans Ethiopic|sans|OFL 1.1|Google|100..900
Noto Sans Georgian|sans|OFL 1.1|Google|100..900
Noto Sans Glagolitic|sans|OFL 1.1|Google|400
Noto Sans Gothic|sans|OFL 1.1|Google|400
Noto Sans Grantha|sans|OFL 1.1|Google|400
Noto Sans Gujarati|sans|OFL 1.1|Google|100..900
Noto Sans Gunjala Gondi|sans|OFL 1.1|Google|400..700
Noto Sans Gurmukhi|sans|OFL 1.1|Google|100..900
Noto Sans Hanifi Rohingya|sans|OFL 1.1|Google|400..700
Noto Sans Hanunoo|sans|OFL 1.1|Google|400
Noto Sans Hatran|sans|OFL 1.1|Google|400
Noto Sans Hebrew|sans|OFL 1.1|Google|100..900
Noto Sans HK|sans|OFL 1.1|Google|100..900
Noto Sans Imperial Aramaic|sans|OFL 1.1|Google|400
Noto Sans Indic Siyaq Numbers|sans|OFL 1.1|Google|400
Noto Sans Inscriptional Pahlavi|sans|OFL 1.1|Google|400
Noto Sans Inscriptional Parthian|sans|OFL 1.1|Google|400
Noto Sans Javanese|sans|OFL 1.1|Google|400..700
Noto Sans JP|sans|OFL 1.1|Google|100..900
Noto Sans Kaithi|sans|OFL 1.1|Google|400
Noto Sans Kannada|sans|OFL 1.1|Google|100..900
Noto Sans Kawi|sans|OFL 1.1|Google|400..700
Noto Sans Kayah Li|sans|OFL 1.1|Google|400..700
Noto Sans Kharoshthi|sans|OFL 1.1|Google|400
Noto Sans Khmer|sans|OFL 1.1|Google|100..900
Noto Sans Khojki|sans|OFL 1.1|Google|400
Noto Sans Khudawadi|sans|OFL 1.1|Google|400
Noto Sans KR|sans|OFL 1.1|Google|100..900
Noto Sans Lao|sans|OFL 1.1|Google|100..900
Noto Sans Lao Looped|sans|OFL 1.1|Google|100..900
Noto Sans Lepcha|sans|OFL 1.1|Google|400
Noto Sans Limbu|sans|OFL 1.1|Google|400
Noto Sans Linear A|sans|OFL 1.1|Google|400
Noto Sans Linear B|sans|OFL 1.1|Google|400
Noto Sans Lisu|sans|OFL 1.1|Google|400..700
Noto Sans Lydian|sans|OFL 1.1|Google|400
Noto Sans Mahajani|sans|OFL 1.1|Google|400
Noto Sans Malayalam|sans|OFL 1.1|Google|100..900
Noto Sans Mandaic|sans|OFL 1.1|Google|400
Noto Sans Manichaean|sans|OFL 1.1|Google|400
Noto Sans Marchen|sans|OFL 1.1|Google|400
Noto Sans Masaram Gondi|sans|OFL 1.1|Google|400
Noto Sans Mayan Numerals|sans|OFL 1.1|Google|400
Noto Sans Medefaidrin|sans|OFL 1.1|Google|400..700
Noto Sans Meetei Mayek|sans|OFL 1.1|Google|100..900
Noto Sans Mende Kikakui|sans|OFL 1.1|Google|400
Noto Sans Meroitic|sans|OFL 1.1|Google|400
Noto Sans Miao|sans|OFL 1.1|Google|400
Noto Sans Modi|sans|OFL 1.1|Google|400
Noto Sans Mongolian|sans|OFL 1.1|Google|400
Noto Sans Mono|sans|OFL 1.1|Google|100..900
Noto Sans Mro|sans|OFL 1.1|Google|400
Noto Sans Multani|sans|OFL 1.1|Google|400
Noto Sans Myanmar|sans|OFL 1.1|Google|100..900
Noto Sans Nabataean|sans|OFL 1.1|Google|400
Noto Sans Nag Mundari|sans|OFL 1.1|Google|400..700
Noto Sans Nandinagari|sans|OFL 1.1|Google|400
Noto Sans New Tai Lue|sans|OFL 1.1|Google|400..700
Noto Sans Newa|sans|OFL 1.1|Google|400
Noto Sans NKo|sans|OFL 1.1|Google|400
Noto Sans NKo Unjoined|sans|OFL 1.1|Google|400..700
Noto Sans Nushu|sans|OFL 1.1|Google|400
Noto Sans Ogham|sans|OFL 1.1|Google|400
Noto Sans Ol Chiki|sans|OFL 1.1|Google|400..700
Noto Sans Old Hungarian|sans|OFL 1.1|Google|400
Noto Sans Old Italic|sans|OFL 1.1|Google|400
Noto Sans Old North Arabian|sans|OFL 1.1|Google|400
Noto Sans Old Permic|sans|OFL 1.1|Google|400
Noto Sans Old Persian|sans|OFL 1.1|Google|400
Noto Sans Old Sogdian|sans|OFL 1.1|Google|400
Noto Sans Old South Arabian|sans|OFL 1.1|Google|400
Noto Sans Old Turkic|sans|OFL 1.1|Google|400
Noto Sans Oriya|sans|OFL 1.1|Google|100..900
Noto Sans Osage|sans|OFL 1.1|Google|400
Noto Sans Osmanya|sans|OFL 1.1|Google|400
Noto Sans Pahawh Hmong|sans|OFL 1.1|Google|400
Noto Sans Palmyrene|sans|OFL 1.1|Google|400
Noto Sans Pau Cin Hau|sans|OFL 1.1|Google|400
Noto Sans PhagsPa|sans|OFL 1.1|Google|400
Noto Sans Phoenician|sans|OFL 1.1|Google|400
Noto Sans Psalter Pahlavi|sans|OFL 1.1|Google|400
Noto Sans Rejang|sans|OFL 1.1|Google|400
Noto Sans Runic|sans|OFL 1.1|Google|400
Noto Sans Samaritan|sans|OFL 1.1|Google|400
Noto Sans Saurashtra|sans|OFL 1.1|Google|400
Noto Sans SC|sans|OFL 1.1|Google|100..900
Noto Sans Sharada|sans|OFL 1.1|Google|400
Noto Sans Shavian|sans|OFL 1.1|Google|400
Noto Sans Siddham|sans|OFL 1.1|Google|400
Noto Sans SignWriting|sans|OFL 1.1|Google|400
Noto Sans Sinhala|sans|OFL 1.1|Google|100..900
Noto Sans Sogdian|sans|OFL 1.1|Google|400
Noto Sans Sora Sompeng|sans|OFL 1.1|Google|400..700
Noto Sans Soyombo|sans|OFL 1.1|Google|400
Noto Sans Sundanese|sans|OFL 1.1|Google|400..700
Noto Sans Sunuwar|sans|OFL 1.1|Google|400
Noto Sans Syloti Nagri|sans|OFL 1.1|Google|400
Noto Sans Symbols|sans|OFL 1.1|Google|100..900
Noto Sans Symbols 2|sans|OFL 1.1|Google|400
Noto Sans Syriac|sans|OFL 1.1|Google|100..900
Noto Sans Syriac Eastern|sans|OFL 1.1|Google|100..900
Noto Sans Syriac Western|sans|OFL 1.1|Google|100..900
Noto Sans Tagalog|sans|OFL 1.1|Google|400
Noto Sans Tagbanwa|sans|OFL 1.1|Google|400
Noto Sans Tai Le|sans|OFL 1.1|Google|400
Noto Sans Tai Tham|sans|OFL 1.1|Google|400..700
Noto Sans Tai Viet|sans|OFL 1.1|Google|400
Noto Sans Takri|sans|OFL 1.1|Google|400
Noto Sans Tamil|sans|OFL 1.1|Google|100..900
Noto Sans Tamil Supplement|sans|OFL 1.1|Google|400
Noto Sans Tangsa|sans|OFL 1.1|Google|400..700
Noto Sans TC|sans|OFL 1.1|Google|100..900
Noto Sans Telugu|sans|OFL 1.1|Google|100..900
Noto Sans Thaana|sans|OFL 1.1|Google|100..900
Noto Sans Thai|sans|OFL 1.1|Google|100..900
Noto Sans Thai Looped|sans|OFL 1.1|Google|100..900
Noto Sans Tifinagh|sans|OFL 1.1|Google|400
Noto Sans Tirhuta|sans|OFL 1.1|Google|400
Noto Sans Ugaritic|sans|OFL 1.1|Google|400
Noto Sans Vai|sans|OFL 1.1|Google|400
Noto Sans Vithkuqi|sans|OFL 1.1|Google|400..700
Noto Sans Wancho|sans|OFL 1.1|Google|400
Noto Sans Warang Citi|sans|OFL 1.1|Google|400
Noto Sans Yi|sans|OFL 1.1|Google|400
Noto Sans Zanabazar Square|sans|OFL 1.1|Google|400
Noto Serif|serif|OFL 1.1|Google|100..900
Noto Serif Ahom|serif|OFL 1.1|Google|400
Noto Serif Armenian|serif|OFL 1.1|Google|100..900
Noto Serif Balinese|serif|OFL 1.1|Google|400
Noto Serif Bengali|serif|OFL 1.1|Google|100..900
Noto Serif Devanagari|serif|OFL 1.1|Google|100..900
Noto Serif Display|serif|OFL 1.1|Google|100..900
Noto Serif Dives Akuru|serif|OFL 1.1|Google|400
Noto Serif Dogra|serif|OFL 1.1|Google|400
Noto Serif Ethiopic|serif|OFL 1.1|Google|100..900
Noto Serif Georgian|serif|OFL 1.1|Google|100..900
Noto Serif Grantha|serif|OFL 1.1|Google|400
Noto Serif Gujarati|serif|OFL 1.1|Google|100..900
Noto Serif Gurmukhi|serif|OFL 1.1|Google|100..900
Noto Serif Hebrew|serif|OFL 1.1|Google|100..900
Noto Serif Hentaigana|serif|OFL 1.1|Google|200..900
Noto Serif HK|serif|OFL 1.1|Google|200..900
Noto Serif JP|serif|OFL 1.1|Google|200..900
Noto Serif Kannada|serif|OFL 1.1|Google|100..900
Noto Serif Khitan Small Script|serif|OFL 1.1|Google|400
Noto Serif Khmer|serif|OFL 1.1|Google|100..900
Noto Serif Khojki|serif|OFL 1.1|Google|400..700
Noto Serif KR|serif|OFL 1.1|Google|200..900
Noto Serif Lao|serif|OFL 1.1|Google|100..900
Noto Serif Makasar|serif|OFL 1.1|Google|400
Noto Serif Malayalam|serif|OFL 1.1|Google|100..900
Noto Serif NP Hmong|serif|OFL 1.1|Google|400..700
Noto Serif Old Uyghur|serif|OFL 1.1|Google|400
Noto Serif Oriya|serif|OFL 1.1|Google|400..700
Noto Serif Ottoman Siyaq|serif|OFL 1.1|Google|400
Noto Serif SC|serif|OFL 1.1|Google|200..900
Noto Serif Sinhala|serif|OFL 1.1|Google|100..900
Noto Serif Tamil|serif|OFL 1.1|Google|100..900
Noto Serif Tangut|serif|OFL 1.1|Google|400
Noto Serif TC|serif|OFL 1.1|Google|200..900
Noto Serif Telugu|serif|OFL 1.1|Google|100..900
Noto Serif Thai|serif|OFL 1.1|Google|100..900
Noto Serif Tibetan|serif|OFL 1.1|Google|100..900
Noto Serif Todhri|serif|OFL 1.1|Google|400
Noto Serif Toto|serif|OFL 1.1|Google|400..700
Noto Serif Vithkuqi|serif|OFL 1.1|Google|400..700
Noto Serif Yezidi|serif|OFL 1.1|Google|400..700
Noto Traditional Nushu|sans|OFL 1.1|Google|300..700
Noto Znamenny Musical Notation|sans|OFL 1.1|Google|400
Nova Cut|display|OFL 1.1|Wojciech Kalinowski|400
Nova Flat|display|OFL 1.1|Wojciech Kalinowski|400
Nova Mono|mono|OFL 1.1|Wojciech Kalinowski|400
Nova Oval|display|OFL 1.1|Wojciech Kalinowski|400
Nova Round|display|OFL 1.1|Wojciech Kalinowski|400
Nova Script|display|OFL 1.1|Wojciech Kalinowski|400
Nova Slim|display|OFL 1.1|Wojciech Kalinowski|400
Nova Square|display|OFL 1.1|Wojciech Kalinowski|400
NTR|sans|OFL 1.1|Purushoth Kumar Guttula|400
Numans|sans|OFL 1.1|Jovanny Lemonad|400
Nunito|sans|OFL 1.1|Vernon Adams, Cyreal, Jacques Le Bailly|200..1000
Nunito Sans|sans|OFL 1.1|Vernon Adams, Jacques Le Bailly, Manvel Shmavonyan, Alexei Vanyashin|200..1000
Nuosu SIL|sans|OFL 1.1|SIL International|400
Odibee Sans|display|OFL 1.1|James Barnard|400
Odor Mean Chey|serif|OFL 1.1|Danh Hong|400
Offside|display|OFL 1.1|Eduardo Tunni|400
Oi|display|OFL 1.1|Kostas Bartsokas|400
Ojuju|sans|OFL 1.1|Ụdị Foundry, Chisaokwu Joboson, Mirko Velimirović|200..800
Old Standard TT|serif|OFL 1.1|Alexey Kryukov|400;700
Oldenburg|display|OFL 1.1|Nicole Fally|400
Ole|handskrift|OFL 1.1|Robert Leuschke|400
Oleo Script|display|OFL 1.1|soytutype fonts|400;700
Oleo Script Swash Caps|display|OFL 1.1|soytutype fonts|400;700
Onest|sans|OFL 1.1|Dmitri Voloshin, Andrey Kudryavtsev|100..900
Oooh Baby|handskrift|OFL 1.1|Robert Leuschke|400
Open Sans|sans|OFL 1.1|Steve Matteson|300..800
Oranienbaum|serif|OFL 1.1|Oleg Pospelov, Jovanny Lemonad|400
Orbit|sans|OFL 1.1|Sooun Cho, JAMO|400
Orbitron|sans|OFL 1.1|Matt McInerney|400..900
Oregano|display|OFL 1.1|Astigmatic|400
Orelega One|display|OFL 1.1|Haruki Wakamatsu|400
Orienta|sans|OFL 1.1|Eduardo Tunni|400
Original Surfer|display|OFL 1.1|Astigmatic|400
Oswald|sans|OFL 1.1|Vernon Adams, Kalapi Gajjar, Cyreal|200..700
Outfit|sans|OFL 1.1|Smartsheet Inc, Rodrigo Fuenzalida|100..900
Over the Rainbow|handskrift|OFL 1.1|Kimberly Geswein|400
Overlock|display|OFL 1.1|Dario Manuel Muhafara|400;700;900
Overlock SC|display|OFL 1.1|Dario Manuel Muhafara|400
Overpass|sans|OFL 1.1|Delve Withrington, Dave Bailey, Thomas Jockin|100..900
Overpass Mono|mono|OFL 1.1|Delve Withrington, Dave Bailey, Thomas Jockin|300..700
Ovo|serif|OFL 1.1|Nicole Fally|400
Oxanium|display|OFL 1.1|Severin Meyer|200..800
Oxygen|sans|OFL 1.1|Vernon Adams|300;400;700
Oxygen Mono|mono|OFL 1.1|Vernon Adams|400
Pacifico|handskrift|OFL 1.1|Vernon Adams, Jacques Le Bailly, Botjo Nikoltchev, Ani Petrova|400
Padauk|sans|OFL 1.1|SIL International|400;700
Padyakke Expanded One|serif|OFL 1.1|James Puckett|400
Palanquin|sans|OFL 1.1|Pria Ravichandran|100;200;300;400;500;600;700
Palanquin Dark|sans|OFL 1.1|Pria Ravichandran|400;500;600;700
Palette Mosaic|display|OFL 1.1|Shibuya Font|400
Pangolin|handskrift|OFL 1.1|Kevin Burke|400
Paprika|display|OFL 1.1|Eduardo Tunni|400
Parastoo|serif|OFL 1.1|Saber Rastikerdar|400..700
Parisienne|handskrift|OFL 1.1|Astigmatic|400
Parkinsans|sans|OFL 1.1|Red Stone|300..800
Passero One|display|OFL 1.1|Viktoriya Grabowska|400
Passion One|display|OFL 1.1|Fontstage|400;700;900
Passions Conflict|handskrift|OFL 1.1|Robert Leuschke|400
Pathway Extreme|sans|OFL 1.1|Eduardo Tunni|100..900
Pathway Gothic One|sans|OFL 1.1|Eduardo Tunni|400
Patrick Hand|handskrift|OFL 1.1|Patrick Wagesreiter|400
Patrick Hand SC|handskrift|OFL 1.1|Patrick Wagesreiter|400
Pattaya|sans|OFL 1.1|Cadson Demak|400
Patua One|display|OFL 1.1|LatinoType|400
Pavanam|sans|OFL 1.1|Tharique Azeez|400
Paytone One|sans|OFL 1.1|Vernon Adams|400
Peddana|serif|OFL 1.1|Appaji Ambarisha Darbha|400
Peralta|serif|OFL 1.1|Astigmatic|400
Permanent Marker|handskrift|Apache 2.0|Font Diner|400
Petemoss|handskrift|OFL 1.1|Robert Leuschke|400
Petit Formal Script|handskrift|OFL 1.1|Impallari Type|400
Petrona|serif|OFL 1.1|Ringo R. Seeber|100..900
Philosopher|sans|OFL 1.1|Jovanny Lemonad|400;700
Phudu|display|OFL 1.1|Dương Trần|300..900
Piazzolla|serif|OFL 1.1|Juan Pablo del Peral, HT Fonts|100..900
Piedra|display|OFL 1.1|Sudtipos|400
Pinyon Script|handskrift|OFL 1.1|Nicole Fally|400
Pirata One|display|OFL 1.1|Rodrigo Fuenzalida, Nicolas Massi|400
Pixelify Sans|display|OFL 1.1|Stefie Justprince|400..700
Plaster|display|OFL 1.1|Sorkin Type|400
Platypi|serif|OFL 1.1|David Sargent|300..800
Play|sans|OFL 1.1|Jonas Hecksher|400;700
Playball|display|OFL 1.1|Robert Leuschke|400
Playfair|serif|OFL 1.1|Claus Eggers Sørensen|300..900
Playfair Display|serif|OFL 1.1|Claus Eggers Sørensen|400..900
Playfair Display SC|serif|OFL 1.1|Claus Eggers Sørensen|400;700;900
Playpen Sans|handskrift|OFL 1.1|TypeTogether, Laura Meseguer, Veronika Burian, José Scaglione, Kostas Bartsokas, Vera Evstafieva, Tom Grace, Yorlmar Campos|100..800
Playpen Sans Arabic|handskrift|OFL 1.1|TypeTogether, Azza Alameddine, Laura Meseguer, Veronika Burian, José Scaglione|100..800
Playpen Sans Deva|handskrift|OFL 1.1|TypeTogether, Pooja Saxena, Gunjan Panchal, Laura Meseguer, Veronika Burian, José Scaglione|100..800
Playpen Sans Hebrew|handskrift|OFL 1.1|TypeTogether, Tom Grace, Laura Meseguer, Veronika Burian, José Scaglione|100..800
Playpen Sans Thai|handskrift|OFL 1.1|TypeTogether, Sirin Gunkloy, Laura Meseguer, Veronika Burian, José Scaglione|100..800
Pliant|sans|OFL 1.1|Non Foundry, Jona Saucedo|100..900
Plus Jakarta Sans|sans|OFL 1.1|Tokotype|200..800
Pochaevsk|display|OFL 1.1|Aleksandr Andreev|400
Podkova|serif|OFL 1.1|Cyreal|400..800
Poetsen One|display|OFL 1.1|Rodrigo Fuenzalida, Pablo Impallari|400
Poiret One|display|OFL 1.1|Denis Masharov|400
Poller One|display|OFL 1.1|Yvonne Schüttler|400
Poltawski Nowy|serif|OFL 1.1|Adam Półtawski, Mateusz Machalski, Borys Kosmynka, Ania Wieluńska|400..700
Poly|serif|OFL 1.1|Nicolás Silva|400
Pompiere|display|OFL 1.1|Karolina Lach|400
Ponnala|display|OFL 1.1|Appaji Ambarisha Darbha|400
Ponomar|display|OFL 1.1|Aleksandr Andreev|400
Pontano Sans|sans|OFL 1.1|Vernon Adams|300..700
Poor Story|display|OFL 1.1|Yoon Design|400
Poppins|sans|OFL 1.1|Indian Type Foundry, Jonny Pinhorn, Ninad Kale|100;200;300;400;500;600;700;800;900
Port Lligat Sans|sans|OFL 1.1|Tipo|400
Port Lligat Slab|serif|OFL 1.1|Tipo|400
Potta One|display|OFL 1.1|Font Zone 108|400
Pragati Narrow|sans|OFL 1.1|Omnibus-Type|400;700
Praise|handskrift|OFL 1.1|Robert Leuschke|400
Prata|serif|OFL 1.1|Cyreal|400
Preahvihear|sans|OFL 1.1|Danh Hong|400
Press Start 2P|display|OFL 1.1|CodeMan38|400
Pridi|serif|OFL 1.1|Cadson Demak|200;300;400;500;600;700
Princess Sofia|handskrift|OFL 1.1|Tart Workshop|400
Prociono|serif|OFL 1.1|Barry Schwartz|400
Prompt|sans|OFL 1.1|Cadson Demak|100;200;300;400;500;600;700;800;900
Prosto One|display|OFL 1.1|Jovanny Lemonad, Pavel Emelyanov|400
Protest Guerrilla|display|OFL 1.1|Octavio Pardo|400
Protest Revolution|display|OFL 1.1|Octavio Pardo|400
Protest Riot|display|OFL 1.1|Octavio Pardo|400
Protest Strike|display|OFL 1.1|Octavio Pardo|400
Proza Libre|sans|OFL 1.1|Jasper de Waard|400;500;600;700;800
PT Mono|mono|OFL 1.1|ParaType|400
PT Sans|sans|OFL 1.1|ParaType|400;700
PT Sans Caption|sans|OFL 1.1|ParaType|400;700
PT Sans Narrow|sans|OFL 1.1|ParaType|400;700
PT Serif|serif|OFL 1.1|ParaType|400;700
PT Serif Caption|serif|OFL 1.1|ParaType|400
Public Sans|sans|OFL 1.1|USWDS, Dan Williams, Pablo Impallari, Rodrigo Fuenzalida|100..900
Puppies Play|handskrift|OFL 1.1|Robert Leuschke|400
Puritan|sans|OFL 1.1|Ben Weiner|400;700
Purple Purse|display|OFL 1.1|Astigmatic|400
Qahiri|sans|OFL 1.1|Khaled Hosny|400
Quando|serif|OFL 1.1|Joana Correia|400
Quantico|sans|OFL 1.1|MADType|400;700
Quattrocento|serif|OFL 1.1|Impallari Type|400;700
Quattrocento Sans|sans|OFL 1.1|Impallari Type|400;700
Questrial|sans|OFL 1.1|Joe Prince, Laura Meseguer|400
Quicksand|sans|OFL 1.1|Andrew Paglinawan|300..700
Quintessential|handskrift|OFL 1.1|Astigmatic|400
Qwigley|handskrift|OFL 1.1|Robert Leuschke|400
Qwitcher Grypen|handskrift|OFL 1.1|Robert Leuschke|400;700
Racing Sans One|display|OFL 1.1|Impallari Type|400
Radio Canada|sans|OFL 1.1|Charles Daoud, Coppers and Brasses, Alexandre Saumier Demers, Jacques Le Bailly|300..700
Radio Canada Big|sans|OFL 1.1|Étienne Aubert Bonn|400..700
Radley|serif|OFL 1.1|Vernon Adams|400
Rajdhani|sans|OFL 1.1|Indian Type Foundry|300;400;500;600;700
Rakkas|display|OFL 1.1|Zeynep Akay|400
Raleway|sans|OFL 1.1|Matt McInerney, Pablo Impallari, Rodrigo Fuenzalida|100..900
Raleway Dots|display|OFL 1.1|Matt McInerney, Pablo Impallari, Rodrigo Fuenzalida, Brenda Gallo|400
Ramabhadra|sans|OFL 1.1|Purushoth Kumar Guttula|400
Ramaraja|serif|OFL 1.1|Appaji Ambarisha Darbha|400
Rambla|sans|OFL 1.1|Martin Sommaruga|400;700
Rammetto One|display|OFL 1.1|Vernon Adams|400
Rampart One|display|OFL 1.1|Fontworks Inc.|400
Ramsina|serif|OFL 1.1|SIL International|400
Ranchers|display|OFL 1.1|Impallari Type|400
Rancho|handskrift|Apache 2.0|Sideshow|400
Ranga|display|OFL 1.1|TipTopTyp|400;700
Rasa|serif|OFL 1.1|Rosetta, Anna Giedryś, David Březina|300..700
Rationale|sans|OFL 1.1|Cyreal|400
Ravi Prakash|display|OFL 1.1|Appaji Ambarisha Darbha|400
Readex Pro|sans|OFL 1.1|Thomas Jockin, Nadine Chahine, Bonnie Shaver-Troup, Santiago Orozco, Héctor Gómez|160..700
Recursive|sans|OFL 1.1|Arrow Type, Stephen Nixon|300..1000
Red Hat Display|sans|OFL 1.1|MCKL|300..900
Red Hat Mono|mono|OFL 1.1|MCKL|300..700
Red Hat Text|sans|OFL 1.1|MCKL|300..700
Red Rose|display|OFL 1.1|Jaikishan Patel|300..700
Redacted|display|OFL 1.1|Christian Naths|400
Redacted Script|display|OFL 1.1|Christian Naths|300;400;700
Reddit Mono|mono|OFL 1.1|Stephen Hutchings, OrangeRed|200..900
Reddit Sans|sans|OFL 1.1|Stephen Hutchings, OrangeRed|200..900
Reddit Sans Condensed|sans|OFL 1.1|Stephen Hutchings, OrangeRed|200..900
Redressed|handskrift|Apache 2.0|Astigmatic|400
Reem Kufi|sans|OFL 1.1|Khaled Hosny, Santiago Orozco|400..700
Reem Kufi Fun|sans|OFL 1.1|Khaled Hosny, Santiago Orozco|400..700
Reem Kufi Ink|sans|OFL 1.1|Khaled Hosny, Santiago Orozco|400
Reenie Beanie|handskrift|OFL 1.1|James Grieshaber|400
Reggae One|display|OFL 1.1|Fontworks Inc.|400
REM|sans|OFL 1.1|Octavio Pardo|100..900
Rethink Sans|sans|OFL 1.1|Hans Thiessen|400..800
Revalia|display|OFL 1.1|Johan Kallas, Mihkel Virkus|400
Rhodium Libre|serif|OFL 1.1|James Puckett|400
Ribeye|display|OFL 1.1|Astigmatic|400
Ribeye Marrow|display|OFL 1.1|Astigmatic|400
Righteous|display|OFL 1.1|Astigmatic|400
Risque|display|OFL 1.1|Astigmatic|400
Road Rage|display|OFL 1.1|Robert Leuschke|400
Roboto|sans|OFL 1.1|Christian Robertson, ParaType, Font Bureau|100..900
Roboto Condensed|sans|OFL 1.1|Christian Robertson|100..900
Roboto Flex|sans|OFL 1.1|Font Bureau, David Berlow, Santiago Orozco, Irene Vlachou, Ilya Ruderman, Yury Ostromentsky, Mikhail Strukov|100..1000
Roboto Mono|mono|OFL 1.1|Christian Robertson|100..700
Roboto Serif|serif|OFL 1.1|Commercial Type, Greg Gazdowicz|100..900
Roboto Slab|serif|Apache 2.0|Christian Robertson|100..900
Rochester|handskrift|Apache 2.0|Sideshow|400
Rock 3D|display|OFL 1.1|Shibuya Font|400
Rock Salt|handskrift|Apache 2.0|Sideshow|400
RocknRoll One|sans|OFL 1.1|Fontworks Inc.|400
Rokkitt|serif|OFL 1.1|Vernon Adams|100..900
Romanesco|handskrift|OFL 1.1|Astigmatic|400
Ropa Sans|sans|OFL 1.1|Botjo Nikoltchev|400
Rosario|sans|OFL 1.1|Omnibus-Type|300..700
Rosarivo|serif|OFL 1.1|Pablo Ugerman|400
Rouge Script|handskrift|OFL 1.1|Sabrina Mariela Lopez|400
Rowdies|display|OFL 1.1|Jaikishan Patel|300;400;700
Rozha One|serif|OFL 1.1|Indian Type Foundry|400
Rubik|sans|OFL 1.1|Hubert and Fischer, Meir Sadan, Cyreal, Daniel Grumer, Omaima Dajani|300..900
Rubik 80s Fade|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Beastly|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Broken Fax|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Bubbles|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Burned|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Dirt|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Distressed|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Doodle Shadow|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Doodle Triangles|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Gemstones|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Glitch|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Glitch Pop|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Iso|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Lines|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Maps|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Marker Hatch|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Maze|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Microbe|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Mono One|sans|OFL 1.1|Hubert and Fischer|400
Rubik Moonrocks|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Pixels|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Puddles|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Scribble|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Spray Paint|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Storm|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Vinyl|display|OFL 1.1|NaN, Luke Prowse|400
Rubik Wet Paint|display|OFL 1.1|NaN, Luke Prowse|400
Ruda|sans|OFL 1.1|Mariela Monsalve, Angelina Sanchez|400..900
Rufina|serif|OFL 1.1|Martin Sommaruga|400;700
Ruge Boogie|handskrift|OFL 1.1|Robert Leuschke|400
Ruluko|sans|OFL 1.1|Ana Sanfelippo, Angélica Díaz, Meme Hernández|400
Rum Raisin|sans|OFL 1.1|Astigmatic|400
Ruslan Display|display|OFL 1.1|Oleg Snarsky, Denis Masharov, Vladimir Rabdu|400
Russo One|sans|OFL 1.1|Jovanny Lemonad|400
Ruthie|handskrift|OFL 1.1|Robert Leuschke|400
Ruwudu|serif|OFL 1.1|SIL International|400;500;600;700
Rye|display|OFL 1.1|Nicole Fally|400
Sacramento|handskrift|OFL 1.1|Astigmatic|400
Sahitya|serif|OFL 1.1|Juan Pablo del Peral|400;700
Sail|display|OFL 1.1|Miguel Hernandez|400
Saira|sans|OFL 1.1|Omnibus-Type|100..900
Saira Condensed|sans|OFL 1.1|Omnibus-Type|100;200;300;400;500;600;700;800;900
Saira Extra Condensed|sans|OFL 1.1|Omnibus-Type|100;200;300;400;500;600;700;800;900
Saira Semi Condensed|sans|OFL 1.1|Omnibus-Type|100;200;300;400;500;600;700;800;900
Saira Stencil|display|OFL 1.1|Hector Gatti, Omnibus-Type|100..900
Salsa|display|OFL 1.1|John Vargas Beltrán|400
Sanchez|serif|OFL 1.1|Daniel Hernandez|400
Sancreek|display|OFL 1.1|Vernon Adams|400
Sankofa Display|sans|OFL 1.1|Batsirai Madzonga|400
Sansation|sans|OFL 1.1|Bernd Montag|300;400;700
Sansita|sans|OFL 1.1|Omnibus-Type|400;700;800;900
Sansita Swashed|display|OFL 1.1|Omnibus-Type|300..900
Sarabun|sans|OFL 1.1|Suppakit Chalermlarp|100;200;300;400;500;600;700;800
Sarala|sans|OFL 1.1|HT Fonts, Andres Torresi|400;700
Sarina|display|OFL 1.1|James Grieshaber|400
Sarpanch|sans|OFL 1.1|Indian Type Foundry|400;500;600;700;800;900
Sassy Frass|handskrift|OFL 1.1|Robert Leuschke|400
Satisfy|handskrift|Apache 2.0|Sideshow|400
Savate|sans|OFL 1.1|Plomb Type, Max Esnée|200..900
Sawarabi Gothic|sans|OFL 1.1|mshio|400
Sawarabi Mincho|serif|OFL 1.1|mshio|400
Scada|sans|OFL 1.1|Jovanny Lemonad|400;700
Scheherazade New|serif|OFL 1.1|SIL International|400;500;600;700
Schibsted Grotesk|sans|OFL 1.1|Bakken & Bæck, Henrik Kongsvoll|400..900
Schoolbell|handskrift|Apache 2.0|Font Diner|400
Science Gothic|sans|OFL 1.1|Thomas Phinney, Vassil Kateliev, Brandon Buerkle|100..900
Scope One|serif|OFL 1.1|Dalton Maag|400
Scoutie Sans|sans|OFL 1.1|Tyler Finck|200..800
Seaweed Script|display|OFL 1.1|Neapolitan|400
Secular One|sans|OFL 1.1|Michal Sahar|400
Sedan|serif|OFL 1.1|Sebastián Salazar|400
Sedan SC|serif|OFL 1.1|Sebastián Salazar|400
Sedgwick Ave|handskrift|OFL 1.1|Pedro Vergani, Kevin Burke|400
Sedgwick Ave Display|handskrift|OFL 1.1|Pedro Vergani, Kevin Burke|400
Sekuya|display|OFL 1.1|SEKUYA|400
Sen|sans|OFL 1.1|Kosal Sen|400..800
Send Flowers|handskrift|OFL 1.1|Robert Leuschke|400
Sevillana|display|OFL 1.1|Brownfox|400
Seymour One|sans|OFL 1.1|Vernon Adams|400
Shadows Into Light|handskrift|OFL 1.1|Kimberly Geswein|400
Shadows Into Light Two|handskrift|OFL 1.1|Kimberly Geswein|400
Shafarik|display|OFL 1.1|Aleksandr Andreev|400
Shalimar|handskrift|OFL 1.1|Robert Leuschke|400
Shantell Sans|display|OFL 1.1|Shantell Martin, Arrow Type, Anya Danilova|300..800
Shanti|sans|OFL 1.1|Vernon Adams|400
Share|sans|OFL 1.1|Carrois Apostrophe|400;700
Share Tech|sans|OFL 1.1|Carrois Apostrophe|400
Share Tech Mono|mono|OFL 1.1|Carrois Apostrophe|400
Shippori Antique|sans|OFL 1.1|FONTDASU|400
Shippori Antique B1|sans|OFL 1.1|FONTDASU|400
Shippori Mincho|serif|OFL 1.1|FONTDASU|400;500;600;700;800
Shippori Mincho B1|serif|OFL 1.1|FONTDASU|400;500;600;700;800
Shizuru|display|OFL 1.1|Shibuya Font|400
Shojumaru|display|OFL 1.1|Astigmatic|400
Short Stack|handskrift|OFL 1.1|James Grieshaber|400
Shrikhand|display|OFL 1.1|Jonny Pinhorn|400
Sigmar|display|OFL 1.1|Vernon Adams|400
Sigmar One|display|OFL 1.1|Vernon Adams|400
Signika|sans|OFL 1.1|Anna Giedryś|300..700
Signika Negative|sans|OFL 1.1|Anna Giedryś|300..700
Silkscreen|display|OFL 1.1|Jason Kottke|400;700
Simonetta|display|OFL 1.1|Brownfox|400;900
Single Day|display|OFL 1.1|DXKorea Inc|400
Sintony|sans|OFL 1.1|Eduardo Rodriguez Tunni|400;700
Sirin Stencil|display|OFL 1.1|Cyreal|400
Sirivennela|sans|OFL 1.1|Appaji Ambarisha Darbha|400
Six Caps|sans|OFL 1.1|Vernon Adams|400
Sixtyfour|mono|OFL 1.1|Jens Kutílek|400
Sixtyfour Convergence|mono|OFL 1.1|Simon Cozens, Jens Kutílek|400
Skranji|display|OFL 1.1|Neapolitan|400;700
Slabo 13px|serif|OFL 1.1|John Hudson|400
Slabo 27px|serif|OFL 1.1|John Hudson|400
Slackey|display|Apache 2.0|Sideshow|400
Slackside One|handskrift|OFL 1.1|Maniackers Design|400
Smokum|display|Apache 2.0|Astigmatic|400
Smooch|handskrift|OFL 1.1|Robert Leuschke|400
Smooch Sans|sans|OFL 1.1|Robert Leuschke|100..900
Smythe|display|OFL 1.1|Vernon Adams|400
SN Pro|sans|OFL 1.1|Tobias Whetton, Supernotes|200..900
Sniglet|display|OFL 1.1|Haley Fiege|400;800
Snippet|sans|OFL 1.1|Gesine Todt|400
Snowburst One|display|OFL 1.1|Annet Stirling|400
Sofadi One|display|OFL 1.1|Botjo Nikoltchev|400
Sofia|handskrift|OFL 1.1|LatinoType|400
Sofia Sans|sans|OFL 1.1|Lettersoup, Botio Nikoltchev, Ani Petrova|1..1000
Sofia Sans Condensed|sans|OFL 1.1|Lettersoup, Botio Nikoltchev, Ani Petrova|1..1000
Sofia Sans Extra Condensed|sans|OFL 1.1|Lettersoup, Botio Nikoltchev, Ani Petrova|1..1000
Sofia Sans Semi Condensed|sans|OFL 1.1|Lettersoup, Botio Nikoltchev, Ani Petrova|1..1000
Solitreo|handskrift|OFL 1.1|Nathan Gross, Bryan Kirschen|400
Solway|serif|OFL 1.1|Mariya Lish, The Northern Block|300;400;500;700;800
Sometype Mono|mono|OFL 1.1|Ryoichi Tsunekawa|400..700
Song Myung|serif|OFL 1.1|JIKJI|400
Sono|sans|OFL 1.1|Tyler Finck|200..800
Sonsie One|display|OFL 1.1|Riccardo De Franceschi|400
Sora|sans|OFL 1.1|Jonathan Barnbrook, Julián Moncada|100..800
Sorts Mill Goudy|serif|OFL 1.1|Barry Schwartz|400
Sour Gummy|sans|OFL 1.1|Stefie Justprince|100..900
Source Code Pro|mono|OFL 1.1|Paul D. Hunt|200..900
Source Sans 3|sans|OFL 1.1|Paul D. Hunt|200..900
Source Serif 4|serif|OFL 1.1|Frank Grießhammer|200..900
Space Grotesk|sans|OFL 1.1|Florian Karsten|300..700
Space Mono|mono|OFL 1.1|Colophon Foundry|400;700
Special Elite|display|Apache 2.0|Astigmatic|400
Special Gothic|sans|OFL 1.1|Alistair McCready|400..700
Special Gothic Condensed One|sans|OFL 1.1|Alistair McCready|400
Special Gothic Expanded One|sans|OFL 1.1|Alistair McCready|400
Spectral|serif|OFL 1.1|Production Type|200;300;400;500;600;700;800
Spectral SC|serif|OFL 1.1|Production Type|200;300;400;500;600;700;800
Spicy Rice|display|OFL 1.1|Astigmatic|400
Spinnaker|sans|OFL 1.1|Elena Albertoni|400
Spirax|display|OFL 1.1|Brenda Gallo|400
Splash|handskrift|OFL 1.1|Robert Leuschke|400
Spline Sans|sans|OFL 1.1|Eben Sorkin, Mirko Velimirović|300..700
Spline Sans Mono|mono|OFL 1.1|Eben Sorkin, Mirko Velimirović|300..700
Squada One|display|OFL 1.1|Joe Prince|400
Square Peg|handskrift|OFL 1.1|Robert Leuschke|400
Sree Krushnadevaraya|serif|OFL 1.1|Purushoth Kumar Guttula|400
Sriracha|handskrift|OFL 1.1|Cadson Demak|400
Srisakdi|display|OFL 1.1|Cadson Demak|400;700
Staatliches|display|OFL 1.1|Brian LaRossa, Erica Carras|400
Stack Sans Headline|sans|OFL 1.1|Koto|200..700
Stack Sans Notch|sans|OFL 1.1|Koto|200..700
Stack Sans Text|sans|OFL 1.1|Koto|200..700
Stalemate|handskrift|OFL 1.1|Astigmatic|400
Stalinist One|display|OFL 1.1|Alexey Maslov, Jovanny Lemonad|400
Stardos Stencil|display|OFL 1.1|Vernon Adams|400;700
Stick|sans|OFL 1.1|Fontworks Inc.|400
Stick No Bills|sans|OFL 1.1|Mooniak|200..800
Stint Ultra Condensed|serif|OFL 1.1|Astigmatic|400
Stint Ultra Expanded|serif|OFL 1.1|Astigmatic|400
STIX Two Text|serif|OFL 1.1|Tiro Typeworks, Ross Mills, John Hudson, Paul Hanslow|400..700
Stoke|serif|OFL 1.1|Nicole Fally|300;400
Story Script|sans|OFL 1.1|Lana Roulhac, Ben Buysse|400
Strait|sans|OFL 1.1|Eduardo Tunni|400
Strichpunkt Sans|sans|OFL 1.1|René Bieder|400..900
Style Script|handskrift|OFL 1.1|Robert Leuschke|400
Stylish|sans|OFL 1.1|AsiaSoft Inc|400
Sue Ellen Francisco|handskrift|OFL 1.1|Kimberly Geswein|400
Suez One|serif|OFL 1.1|Michal Sahar|400
Sulphur Point|sans|OFL 1.1|Dale Sattler|300;400;700
Sumana|serif|OFL 1.1|Cyreal|400;700
Sunflower|sans|OFL 1.1|JIKJISOFT|300;500;700
Sunshiney|handskrift|Apache 2.0|Sideshow|400
Supermercado One|display|OFL 1.1|James Grieshaber|400
Sura|serif|OFL 1.1|Carolina Giovagnoli|400;700
Suranna|serif|OFL 1.1|Purushoth Kumar Guttula|400
Suravaram|serif|OFL 1.1|Purushoth Kumar Guttula|400
SUSE|sans|OFL 1.1|René Bieder|100..900
SUSE Mono|sans|OFL 1.1|René Bieder|100..800
Suwannaphum|serif|OFL 1.1|Danh Hong|100;300;400;700;900
Swanky and Moo Moo|handskrift|OFL 1.1|Kimberly Geswein|400
Syncopate|sans|Apache 2.0|Astigmatic|400;700
Syne|sans|OFL 1.1|Bonjour Monde, Lucas Descroix, George Triantafyllakos|400..800
Syne Mono|mono|OFL 1.1|Bonjour Monde, Lucas Descroix|400
Syne Tactile|display|OFL 1.1|Bonjour Monde, Lucas Descroix|400
Tac One|sans|OFL 1.1|Afrotype, Seyi Olusanya, Eyiyemi Adegbite, David Udoh, Mirko Velimirović|400
Tagesschrift|display|OFL 1.1|Yanone|400
Tai Heritage Pro|serif|OFL 1.1|SIL International|400;700
Tajawal|sans|OFL 1.1|Boutros Fonts, Mourad Boutros, Soulaf Khalifeh|200;300;400;500;700;800;900
Tangerine|handskrift|OFL 1.1|Toshi Omagari|400;700
Tapestry|handskrift|OFL 1.1|Robert Leuschke|400
Taprom|display|OFL 1.1|Danh Hong, Neapolitan|400
TASA Explorer|sans|OFL 1.1|Local Remote, Weizhong Zhang|400..800
TASA Orbiter|sans|OFL 1.1|Local Remote, Weizhong Zhang|400..800
Tauri|sans|OFL 1.1|Yvonne Schüttler|400
Taviraj|serif|OFL 1.1|Cadson Demak|100;200;300;400;500;600;700;800;900
Teachers|sans|OFL 1.1|Alfredo Marco Pradil, Chank Diesel|400..800
Teko|sans|OFL 1.1|Indian Type Foundry|300..700
Tektur|display|OFL 1.1|Adam Jagosz|400..900
Telex|sans|OFL 1.1|HT Fonts, Andres Torresi|400
Tenali Ramakrishna|sans|OFL 1.1|Appaji Ambarisha Darbha|400
Tenor Sans|sans|OFL 1.1|Denis Masharov|400
Text Me One|sans|OFL 1.1|Julia Petretta|400
Texturina|serif|OFL 1.1|Guillermo Torres, Omnibus-Type|100..900
Thasadith|sans|OFL 1.1|Cadson Demak|400;700
The Girl Next Door|handskrift|OFL 1.1|Kimberly Geswein|400
The Nautigal|handskrift|OFL 1.1|Robert Leuschke|400;700
Tienne|serif|OFL 1.1|Vernon Adams|400;700;900
TikTok Sans|sans|OFL 1.1|Grilli Type, Contrast Foundry, Type Network|300..900
Tillana|display|OFL 1.1|Indian Type Foundry|400;500;600;700;800
Tilt Neon|display|OFL 1.1|Andy Clymer|400
Tilt Prism|display|OFL 1.1|Andy Clymer|400
Tilt Warp|display|OFL 1.1|Andy Clymer|400
Timmana|sans|OFL 1.1|Appaji Ambarisha Darbha|400
Tinos|serif|OFL 1.1|Steve Matteson|400;700
Tiny5|sans|OFL 1.1|Stefan Schmidt|400
Tiro Bangla|serif|OFL 1.1|Tiro Typeworks, John Hudson, Fiona Ross, Neelakash Kshetrimayum|400
Tiro Devanagari Hindi|serif|OFL 1.1|Tiro Typeworks, John Hudson, Fiona Ross, Paul Hanslow|400
Tiro Devanagari Marathi|serif|OFL 1.1|Tiro Typeworks, John Hudson, Fiona Ross, Paul Hanslow|400
Tiro Devanagari Sanskrit|serif|OFL 1.1|Tiro Typeworks, John Hudson, Fiona Ross, Paul Hanslow|400
Tiro Gurmukhi|serif|OFL 1.1|Tiro Typeworks, John Hudson, Fiona Ross, Paul Hanslow|400
Tiro Kannada|serif|OFL 1.1|Tiro Typeworks, John Hudson, Fiona Ross, Kaja Słojewska|400
Tiro Tamil|serif|OFL 1.1|Tiro Typeworks, Fernando Mello, Fiona Ross, Kaja Słojewska|400
Tiro Telugu|serif|OFL 1.1|Tiro Typeworks, John Hudson, Fiona Ross, Kaja Słojewska|400
Tirra|sans|OFL 1.1|SIL International|400;500;600;700;800;900
Titan One|display|OFL 1.1|Rodrigo Fuenzalida|400
Titillium Web|sans|OFL 1.1|Accademia di Belle Arti di Urbino|200;300;400;600;700;900
Tomorrow|sans|OFL 1.1|Tony de Marco, Monica Rizzolli|100;200;300;400;500;600;700;800;900
Tourney|display|OFL 1.1|Tyler Finck, ETC|100..900
Trade Winds|display|OFL 1.1|Sideshow|400
Train One|display|OFL 1.1|Fontworks Inc.|400
Triodion|display|OFL 1.1|Aleksandr Andreev|400
Trirong|serif|OFL 1.1|Cadson Demak|100;200;300;400;500;600;700;800;900
Trispace|sans|OFL 1.1|Tyler Finck, ETC|100..800
Trocchi|serif|OFL 1.1|Vernon Adams|400
Trochut|display|OFL 1.1|Andreu Balius|400;700
Truculenta|sans|OFL 1.1|Omnibus-Type|100..900
Trykker|serif|OFL 1.1|Magnus Gaarde|400
Tsukimi Rounded|sans|OFL 1.1|Takashi Funayama|300;400;500;600;700
Tuffy|sans|OFL 1.1|Thatcher Ulrich|400;700
Tulpen One|display|OFL 1.1|Naima Ben Ayed|400
Turret Road|display|OFL 1.1|Dale Sattler|200;300;400;500;700;800
Twinkle Star|handskrift|OFL 1.1|Robert Leuschke|400
Ubuntu|sans|UFL 1.0|Dalton Maag|300;400;500;700
Ubuntu Condensed|sans|UFL 1.0|Dalton Maag|400
Ubuntu Mono|mono|UFL 1.0|Dalton Maag|400;700
Ubuntu Sans|sans|UFL 1.0|Dalton Maag|100..800
Ubuntu Sans Mono|mono|UFL 1.0|Dalton Maag|400..700
Uchen|serif|OFL 1.1|Christopher J. Fynn|400
Ultra|serif|Apache 2.0|Astigmatic|400
Unbounded|sans|OFL 1.1|NaN|200..900
Uncial Antiqua|display|OFL 1.1|Astigmatic|400
Underdog|display|OFL 1.1|Sergey Steblina, Jovanny Lemonad|400
Unica One|display|OFL 1.1|Eduardo Tunni|400
UnifrakturCook|display|OFL 1.1|j. 'mach' wust|700
UnifrakturMaguntia|display|OFL 1.1|j. 'mach' wust|400
Unkempt|display|Apache 2.0|Sideshow|400;700
Unlock|display|OFL 1.1|Eduardo Tunni|400
Unna|serif|OFL 1.1|Omnibus-Type|400;700
UoqMunThenKhung|serif|OFL 1.1|Moonlit Owen|400
Updock|handskrift|OFL 1.1|Robert Leuschke|400
Urbanist|sans|OFL 1.1|Corey Hu|100..900
Valley Sans|sans|OFL 1.1|Niklas Ekholm, Lari Mörö|100..900
Vampiro One|display|OFL 1.1|Riccardo De Franceschi|400
Varela|sans|OFL 1.1|Joe Prince|400
Varela Round|sans|OFL 1.1|Joe Prince|400
Varta|sans|OFL 1.1|Joana Correia, Viktoriya Grabowska, Eben Sorkin|300..700
Vast Shadow|serif|OFL 1.1|Nicole Fally|400
Vazirmatn|sans|OFL 1.1|Saber Rastikerdar|100..900
Vend Sans|sans|OFL 1.1|Bloom Type Foundry, Baptiste Guesnon|300..700
Vesper Libre|serif|OFL 1.1|Mota Italic|400;500;700;900
Viaoda Libre|display|OFL 1.1|Gydient, ViệtAnh Nguyễn|400
Vibes|display|OFL 1.1|AbdElmomen Kadhim (blueMix)|400
Vibur|handskrift|OFL 1.1|Johan Kallas|400
Victor Mono|mono|OFL 1.1|Rune Bjørnerås|100..700
Vidaloka|serif|OFL 1.1|Cyreal|400
Viga|sans|OFL 1.1|Fontstage|400
Vina Sans|display|OFL 1.1|Nguyen Type|400
Voces|sans|OFL 1.1|Ana Paula Megda, Pablo Ugerman|400
Volkhov|serif|OFL 1.1|Cyreal|400;700
Vollkorn|serif|OFL 1.1|Friedrich Althausen|400..900
Vollkorn SC|serif|OFL 1.1|Friedrich Althausen|400;600;700;900
Voltaire|sans|OFL 1.1|Yvonne Schüttler|400
VT323|mono|OFL 1.1|Peter Hull|400
Vujahday Script|handskrift|OFL 1.1|Robert Leuschke|400
Waiting for the Sunrise|handskrift|OFL 1.1|Kimberly Geswein|400
Wallpoet|display|OFL 1.1|Lars Berggren|400
Walter Turncoat|handskrift|Apache 2.0|Sideshow|400
Warnes|display|OFL 1.1|Eduardo Tunni|400
Water Brush|handskrift|OFL 1.1|Robert Leuschke|400
Waterfall|handskrift|OFL 1.1|Robert Leuschke|400
WDXL Lubrifont JP N|sans|OFL 1.1|NightFurySL2001|400
WDXL Lubrifont SC|sans|OFL 1.1|NightFurySL2001|400
WDXL Lubrifont TC|sans|OFL 1.1|NightFurySL2001|400
Wellfleet|serif|OFL 1.1|Riccardo De Franceschi|400
Wendy One|sans|OFL 1.1|Alejandro Inler|400
Whisper|handskrift|OFL 1.1|Robert Leuschke|400
WindSong|handskrift|OFL 1.1|Robert Leuschke|400;500
Winky Rough|sans|OFL 1.1|Typofactur|300..900
Winky Sans|sans|OFL 1.1|Typofactur|300..900
Wire One|sans|OFL 1.1|Cyreal|400
Wittgenstein|serif|OFL 1.1|Jörg Drees|400..900
Wix Madefor Display|sans|OFL 1.1|Dalton Maag|400..800
Wix Madefor Text|sans|OFL 1.1|Dalton Maag|400..800
Work Sans|sans|OFL 1.1|Wei Huang|100..900
Workbench|mono|OFL 1.1|Jens Kutílek|400
Xanh Mono|mono|OFL 1.1|Yellow Type, Lâm Bảo, Duy Dao|400
Yaldevi|sans|OFL 1.1|Mooniak|200..700
Yanone Kaffeesatz|sans|OFL 1.1|Yanone, Cyreal|200..700
Yantramanav|sans|OFL 1.1|Erin McLaughlin|100;300;400;500;700;900
Yarndings 12|display|OFL 1.1|Sarah Cadigan-Fried|400
Yarndings 12 Charted|display|OFL 1.1|Sarah Cadigan-Fried|400
Yarndings 20|display|OFL 1.1|Sarah Cadigan-Fried|400
Yarndings 20 Charted|display|OFL 1.1|Sarah Cadigan-Fried|400
Yatra One|display|OFL 1.1|Catherine Leigh Schmidt|400
Yellowtail|handskrift|Apache 2.0|Astigmatic|400
Yeon Sung|display|OFL 1.1|Woowahan brothers|400
Yeseva One|display|OFL 1.1|Jovanny Lemonad|400
Yesteryear|handskrift|OFL 1.1|Astigmatic|400
Yomogi|handskrift|OFL 1.1|Satsuyako|400
Young Serif|serif|OFL 1.1|Bastien Sozeau|400
Yrsa|serif|OFL 1.1|Rosetta, Anna Giedryś, David Březina|300..700
Ysabeau|sans|OFL 1.1|Christian Thalmann|1..1000
Ysabeau Infant|sans|OFL 1.1|Christian Thalmann|1..1000
Ysabeau Office|sans|OFL 1.1|Christian Thalmann|1..1000
Ysabeau SC|sans|OFL 1.1|Christian Thalmann|1..1000
Yuji Boku|serif|OFL 1.1|Kinuta Font Factory|400
Yuji Hentaigana Akari|handskrift|OFL 1.1|Kinuta Font Factory|400
Yuji Hentaigana Akebono|handskrift|OFL 1.1|Kinuta Font Factory|400
Yuji Mai|serif|OFL 1.1|Kinuta Font Factory|400
Yuji Syuku|serif|OFL 1.1|Kinuta Font Factory|400
Yusei Magic|sans|OFL 1.1|Tanukizamurai|400
Yuyu|handskrift|OFL 1.1|Julia García López|400
Yuyu Short|handskrift|OFL 1.1|Julia García López|400
Zain|sans|OFL 1.1|Boutros Fonts|200;300;400;700;800;900
Zalando Sans|sans|OFL 1.1|Jakob Ekelund, KH Type, Zalando|200..900
Zalando Sans Expanded|sans|OFL 1.1|Jakob Ekelund, KH Type, Zalando|200..900
Zalando Sans SemiExpanded|sans|OFL 1.1|Jakob Ekelund, KH Type, Zalando|200..900
ZCOOL KuaiLe|sans|OFL 1.1|Liu Bingke, Yang Kang, Wu Shaojie|400
ZCOOL QingKe HuangYou|sans|OFL 1.1|Zheng Qingke|400
ZCOOL XiaoWei|sans|OFL 1.1|Li Dawei|400
Zen Antique|serif|OFL 1.1|Yoshimichi Ohira|400
Zen Antique Soft|serif|OFL 1.1|Yoshimichi Ohira|400
Zen Dots|display|OFL 1.1|Yoshimichi Ohira|400
Zen Kaku Gothic Antique|sans|OFL 1.1|Yoshimichi Ohira|300;400;500;700;900
Zen Kaku Gothic New|sans|OFL 1.1|Yoshimichi Ohira|300;400;500;700;900
Zen Kurenaido|sans|OFL 1.1|Yoshimichi Ohira|400
Zen Loop|display|OFL 1.1|Yoshimichi Ohira|400
Zen Maru Gothic|sans|OFL 1.1|Yoshimichi Ohira|300;400;500;700;900
Zen Old Mincho|serif|OFL 1.1|Yoshimichi Ohira|400;500;600;700;900
Zen Tokyo Zoo|display|OFL 1.1|Yoshimichi Ohira|400
Zeyada|handskrift|OFL 1.1|Kimberly Geswein|400
Zhi Mang Xing|handskrift|OFL 1.1|Wei Zhimang|400
Zilla Slab|serif|OFL 1.1|Typotheque|300;400;500;600;700
Zilla Slab Highlight|serif|OFL 1.1|Typotheque|400;700`
