// Writes `src/editor/google-fonts.ts` — the list the picker searches (#329, L27).
//
// Run by hand: `pnpm --filter @byd/web exec tsx scripts/google-fonts.ts`.
//
// It is generated and not fetched because the two endpoints that could answer «which families
// are there» send no `Access-Control-Allow-Origin`: a browser cannot read
// `fonts.google.com/metadata/fonts`, and the only CORS-open addresses Google has are `css2` and
// `fonts.gstatic.com`, which answer about a family you already know the name of. So the names
// travel with the build and the faces come from Google, which is also what the approved
// prototype did.
//
// The licence is not in the metadata at all, and it is the field L27 turns on — a catalog entry
// exists to answer what an uploaded file cannot. It is read off the `google/fonts` repository,
// where the licence is the directory a family lives in: `ofl`, `apache`, `ufl`.
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

const CATEGORIES: Record<string, string> = { Serif: 'serif', 'Sans Serif': 'sans', Display: 'display', Handwriting: 'handskrift', Monospace: 'mono' }
const LICENCES: Record<string, string> = { ofl: 'OFL 1.1', apache: 'Apache 2.0', ufl: 'UFL 1.0' }

type Family = { family: string; category: string; subsets: string[]; designers: string[]; fonts: Record<string, unknown>; axes: { tag: string; min: number; max: number }[] }

const slug = (family: string): string => family.toLowerCase().replace(/[^a-z0-9]/g, '')

async function licenceBySlug(): Promise<Map<string, string>> {
  const root = (await (await fetch('https://api.github.com/repos/google/fonts/git/trees/main')).json()) as { tree: { path: string; sha: string; type: string }[] }
  const out = new Map<string, string>()
  for (const [dir, licence] of Object.entries(LICENCES)) {
    const node = root.tree.find((t) => t.path === dir && t.type === 'tree')
    if (!node) throw new Error(`google/fonts has no ${dir}/`)
    const tree = (await (await fetch(`https://api.github.com/repos/google/fonts/git/trees/${node.sha}`)).json()) as { tree: { path: string }[]; truncated: boolean }
    if (tree.truncated) throw new Error(`${dir}/ came back truncated`)
    for (const entry of tree.tree) out.set(entry.path, licence)
  }
  return out
}

const catalog = (await (await fetch('https://fonts.google.com/metadata/fonts')).json()) as { familyMetadataList: Family[] }
const licences = await licenceBySlug()

const rows: { family: string; line: string }[] = []
const unlicensed: string[] = []
for (const f of catalog.familyMetadataList) {
  // A family with no latin cut cannot set a card the tool itself is written in, and it is a
  // third of the list — so it is left out rather than offered and then found wanting.
  if (!f.subsets.includes('latin')) continue
  const category = CATEGORIES[f.category]
  if (!category) continue
  const licence = licences.get(slug(f.family))
  if (!licence) {
    // A family whose licence cannot be stated is exactly the family a catalog entry has no
    // business claiming to know the answer for (L27), so it is left out and named here.
    unlicensed.push(f.family)
    continue
  }
  const wght = f.axes.find((a) => a.tag === 'wght')
  const weights = wght ? `${wght.min}..${wght.max}` : Object.keys(f.fonts).filter((w) => /^\d+$/.test(w)).sort((a, b) => Number(a) - Number(b)).join(';')
  if (weights === '') continue
  rows.push({ family: f.family, line: [f.family, category, licence, f.designers.join(', '), weights].join('|') })
}
// By the family name and not by the whole line: `Cinzel|…` against `Cinzel Decorative|…` sorts
// on the separator, and a collator does not read `|` the way it reads a space.
rows.sort((a, b) => a.family.localeCompare(b.family, 'en'))
const lines = rows.map((r) => r.line)

const generated = new Date().toISOString().slice(0, 10)

const out = `// GENERATED by scripts/google-fonts.ts — do not edit by hand.
//
// Google Fonts as of ${generated}: ${lines.length} families with a latin cut, each with the
// licence it is published under, who drew it, and the weights it can be asked for. One family
// per line, \`family|category|licence|by|weights\` (see \`font-catalog.ts\`).
//
// Loaded only by the dynamic import in \`FontCatalog.tsx\`, so none of this weight is on the
// editor's first paint and none of it is fetched from Google (#329, L27, DRIFT §12).
//
// The day this file was written, so the age of the list can be read without running anything.
// \`font-catalog.test.ts\` goes red six months after it and names the command that fixes it
// (#370, L27) — this list has no scheduler behind it and ages only when nobody looks.
export const GOOGLE_FONTS_GENERATED = '${generated}'

export const GOOGLE_FONTS = \`${lines.join('\n')}\`
`
writeFileSync(join(import.meta.dirname, '..', 'src', 'editor', 'google-fonts.ts'), out)
// What was written goes on stdout; what was *lost* goes on stderr, named one per line and never
// abridged (#370). A list that silently shrinks is the failure mode the owner asked to see, and
// stderr is what survives a run whose stdout is piped or swallowed by CI. It is not an error —
// six families without a stateable licence is the expected state and the script still exits 0 —
// but a growing count is meant to be impossible to miss.
console.log(`${lines.length} families written to src/editor/google-fonts.ts, stamped ${generated}`)
console.error(`${unlicensed.length} families left out for want of a licence that could be stated:`)
for (const family of unlicensed) console.error(`  ${family}`)
